### ISSUE TITLE
Extra instructions not showing

### ISSUE THREAD

**Issue by Jorieke** [hotosm/tasking-manager#1030]
I just wanted to publish task 4031, but the extra instructions added are not showing up. They should show up like in task 3402 once you have selected a task for mapping you will have there extra instructions.

**Comment by bgirardot** [comment]
@Jorieke 3402 does not have any extra instructions https://tasks.hotosm.org/project/3402

It would be good to see the one where it does work, if you could please.

As you say, they do not appear in 4031.

**Comment by Jorieke** [comment]
Sorry made a mistake, it is 3420

**Comment by bgirardot** [comment]
Still looking at this @Jorieke

**Comment by bgirardot** [comment]
@Jorieke Oh, I see the problem. The issue is caused because the task square is a custom task square or just not a square task in the case of tasks that are not square due to AoI trimming.

I cloned the project, same everything but did not trim to the aoi and everything looks like it works:

https://tasks.hotosm.org/project/4064

I saw what I thought was a typo in the url and fixed it, but if it was not a typo you will need to fix it back.

I thought there was a missing / in the url between {z} and Final:

{x}/{y}/{z}/Final-S-Kivu-Health.osm
{x}/{y}/{z}Final-S-Kivu-Health.osm

**Comment by Jorieke** [comment]
Only had a chance to look at it now. Thanks so much for figuring this out!
