### ISSUE TITLE
auto unlock too early

### ISSUE THREAD

**Issue by MaestroGlanz** [hotosm/tasking-manager#1084]
This is super annoying. My tasks get auto unlocked all time, because it "takes me too long". If this happens, I would like to know at least, how long it takes. And this should be in the protocol also. Otherwise it could happen, that I edit, get auto unlocked and another person starts editing in the same area.

**Comment by ethan-nelson** [comment]
Hi @MaestroGlanz we have just merged an update into our bleeding-edge release that adds the auto-unlock timer to the task window while one is checked out. This change will be deployed in the near future to the live Tasking Manager, but for reference in the mean time, the timeout is two hours. I am going to go ahead and close this issue since it should be fixed by the change, but please reopen it if you find that feature to be lacking when it  is deployed.

Sample of what it will look like:

![](https://user-images.githubusercontent.com/36561389/43171785-62e32baa-8fc9-11e8-9755-3d2f2a242784.png)
