### ISSUE TITLE
Options to map a task after marking it for Bad Imagery

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1199]
### Current behaviour
Once a task is marked as `bad imagery`,  there's no option to choose `Start mapping` task again. Only choice is to validate the task.

![image](https://user-images.githubusercontent.com/12103383/46462125-c79c8b00-c7ea-11e8-9bb6-c7d1e5a245c6.png)

### Expected behvaiour
Since the task is not mapped, I still expect a choice to lock the task for mapping. Validation options should be availble only if the task is marked as completely mapped.

**Comment by ethan-nelson** [comment]
Hi @ramyaragupathy, from discussions in the past, I believe that there is value in marking tasks as bad imagery and "validating" that so that project managers know of areas that will not have data. I think there is some discussion relevant to that on https://github.com/hotosm/tasking-manager/issues/551 , but that ticket brings up a relevant point that even if you do "validate" bad imagery, there is no real indicator of that unless if you look at task history.

**Comment by willemarcel** [comment]
TM4 allows us to undo a bad imagery and then map it
