### ISSUE TITLE
Switching from validate to map causes jump

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1225]
If you have the validating tab open and select a project that is in a mapping state, the task will direct you that it can't be validated. Here, a user will possibly click the map tab to try and map the task. When you click on the map tab, though, the browser jumps to the very top of the page instead of the top of the contributing window. This is in Firefox 59 on Ubuntu.

**Comment by Hulios** [comment]
Hi @ethan-nelson 
It happens because there is empty anchor set in tab headers:
https://github.com/hotosm/tasking-manager/blob/200b155f19245b7ff2b24a56a522eb8eccb70da7/client/app/project/project.html#L128
What is the expected behavior when you click on the tab?
- jump to the top of contributing window
- don't jump at all

And what should happen when you go to comments tab? Should it jump to the latest comment on the bottom, or should it be the same behavior as in other tabs?

**Comment by ethan-nelson** [comment]
I can't actually reproduce this now -_- I'm not sure exactly what the flow was that got me to that case...it may have had an extra step of marking a task as done or validated prior to clicking a new task and then clicking another tab header. In any case, my preference would be to not jump at all.

**Comment by Hulios** [comment]
This are steps that I took to reproduce it:
- Open project containing comments
- After one second, URL should be changed, and contain '#bottom' in the end
- Scroll down and click on the tab header
