### ISSUE TITLE
Better permission policies for project management

### ISSUE THREAD

**Issue by cgiovando** [hotosm/tasking-manager#1347]
At the moment, any project manager can edit any project. We should restrict these permissions to admins only or set new policies for adding project managers to each project for collaborative editing (see also #969).

Projects also don't show metadata about who last edited (regression from TM2?).

**Comment by russdeffner** [comment]
This has become urgent for me, every time I turn around something has been changed with activation projects and I have no way to track who or how it happened. I cannot fully manage a response with the way this is 'free-for-all' and un-tracked. I'm not sure we should restrict, because there are times I want someone else to edit my projects (and of course Admins should be able to no matter what) but for sure being able to tell who is changing things is absolutely essential. (yes, writing this a bit annoyed)

**Comment by Vaomatua** [comment]
Thanks @cgiovando and @russdeffner This would be especially helpful with multiple projects ongoing and several tasks being "fixed" by unknown individuals. Perhaps granting editing permissions to specific individuals might be easier to implement?
Thanks
Emmor

**Comment by xamanu** [comment]
@JorgeMartinezG is working on it in https://github.com/hotosm/tasking-manager/pull/1574

The teams implementation #1591 will improve this, too.

**Comment by xamanu** [comment]
Connecting this with #969 that is related to this topic, too.
