### ISSUE TITLE
ready2go: new Partially Mapped and Review Requested task statuses

### ISSUE THREAD

**Issue by nrotstan** [hotosm/tasking-manager#1385]
> Note: this feature has been implemented, but not yet submitted as a PR

* Offer new Partially Mapped task status that allows a user to indicate they have mapped some of the task, but not yet completed it
* If a validator attempts to mark a task in Partially Mapped status as validated/invalidated, show a warning noting the task is not yet complete and ask for confirmation
* Offer new Review Requested task status for when a mapper is unsure of their work, allowing validators to hone in on potentially problematic work or at least be aware that a task likely requires additional attention during validation
* Highlight tasks in Review Requested status in orange on the map

<img width="911" alt="partially_mapped" src="https://user-images.githubusercontent.com/445970/54146091-783b3600-43ec-11e9-8610-6d9c29c08316.png">

<img width="554" alt="not_completely_mapped" src="https://user-images.githubusercontent.com/445970/54145831-f64b0d00-43eb-11e9-8ef7-a422796568b7.png">

**Comment by zlavergne** [comment]
I've got some input on the design of these features.

I feel like the color for `Mapped` and `Partially Mapped` are too similar. I think a hashed pattern with the color for `Mapped` and white would portray the idea of an incomplete task more clearly.

> * Offer new Review Requested task status for when a mapper is unsure of their work, allowing validators to hone in on potentially problematic work or at least be aware that a task likely requires additional attention during validation
> * Highlight tasks in Review Requested status in orange on the map

Since `Review Requested` only applies to the validation step we could only render `Review Requested` when the validator tab is selected and show it as `Mapped` otherwise. I'm worried new mappers will get confused/discouraged if they start seeing similar colors. Alternatively, `Review Requested` could be an icon (perhaps an `!`) instead of a new color.

**Comment by xamanu** [comment]
I agree `Review requested` is a very useful new state.

To me `Mapped` and `Partially mapped` are fundamentally different (one requires a validator to take next actions, the other a mapper to take next actions). But i think `Partially mapped` and `Invalidated` (or `More work needed`, see #1376) are very similar, because both require a mapper to touch it again. And I think the colour of this should be similar to the white `Ready to map`. Both are for the same people to pick up - the mappers.

<p align="center"><img src="https://user-images.githubusercontent.com/97706/58243220-c3a08780-7d3f-11e9-8810-23d8453bf852.png" /></p>

What do you think about this?
A related conversation is also happening in #1257.
