### ISSUE TITLE
Add extra code to enable proper build of Tasking-Manager

### ISSUE THREAD

**Issue by theprover97** [hotosm/tasking-manager#1474]
We are unable to properly setup the Tasking-Manager app after running the "docker-compose up -d" command as mentioned in the Readme file. The docker-compose works fine but opening the server at mentioned port in the browser shows Error 404. This prevents beginners from getting involved in contributions right away. We can add new suitable code to solve this.

**Comment by ramyaragupathy** [comment]
Can you please add more information about the environment you're working in @theprover97 ?

**Comment by xamanu** [comment]
I think this is about the building of the front-end after spinning up the `docker-compose`.

Probably this can be fixed by tackling two issues:

* Document the command `docker exec -it tasking-manager_app_1 /bin/bash -c 'cd client && npm install && gulp build'`
* Automatize the frontend building when spinning up `docker-compose up` for the first time.

**Comment by xamanu** [comment]
I think this has been addressed with #1498
