### ISSUE TITLE
Upgrade postgres database

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1563]
Let's move on to a more recent version of the database. We are currently running production on 9.5.x, and our development environments run well on 10.x or 11.x. Can we move on and upgrade the database?

What implications does this have on our infrastructure? @arunasank and @dakotabenjamin

**Comment by arunasank** [comment]
Resources: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html

**Comment by arunasank** [comment]
👋 I managed to successfully upgrade an experimental RDS database dump to 11.3. In the current elastic beanstalk setup, the RDS is setup outside of the EBS - this is the reason for us having multiple postgres versions. In the CloudFormation template, since the RDS is part of the CFN template, we won't have this issue.

While it is possible to directly upgrade the version on the AWS RDS, I propose that we retrieve the latest dumps of the database, upgrade the RDS versions on the dump, and load the resulting database into a fresh RDS database as part of the CloudFormation template. Here's how I propose we go about the database migrations and new database setup:

Have a day - perhaps a Sunday would work well - when we request users to abstain from using the HOT tasking-manager instances
1. Upgrade all the RDS versions on the databases
2. Run the data audit cleanup on the production database
3. Load the RDS databases with the upgraded and audited data dump

I expect the process to take at most 2 hours for each database instance, since I have well defined scripts and documentation for the process. Will wait for the ✅ and thoughts from you @xamanu, before deciding on a date. Currently, working on testing this out on the teachosm database.

**Comment by xamanu** [comment]
I suggest to do the upgrade together with rolling out version 3.3 of the TM. Please have a look at the MissingMaps website for scheduled mapathons and ask @russdeffner for a good day/moment to do the migration.

**Comment by russdeffner** [comment]
I think we're back to fairly normal ops; so good to just check for mapathons and I think @dakotabenjamin has a good lull-time determined (or can). Would just suggest if we expect this to be a bit more involved that we message well in advance, just in case.

**Comment by arunasank** [comment]
Hi friends, I am stuck pretty royally on this issue. 

## What is the issue
The dump that I generate using a combination of `pg_upgrade` and `pg_dump`, and then try to restore on the RDS database using either psql or pg_restore, always fails.

## Why
My sense is a mismatch between the postgres and postgis versions on Ubuntu and the RDS, but I am still seeing issues even after fixing this dependency difference. 
* Here's an example of the errors I see, from `pg_restore`: https://paste.fedoraproject.org/paste/V-f~PxlQgeg8~ovffANSYg
* The errors on using psql with the dump are also similar, with there being no owner for postgis, and then a series of warnings about privileges not being accorded to postgis functions

## Doc
Here's the doc to generate the dump on an ec2: https://paper.dropbox.com/doc/RDS-Upgrade--AdD8b7bOw46gJqjuYVhRadnhAg-Rygq6g8LnFTGTJg2s8NVc

Per chat with @xamanu, I downgraded the version of postgresql I was trying to upgrade to to 10.7, (from 11.2), because of complications installing the 11.2 version on debian, but there might be a solution to that.

Can someone else give this a shot? I think you'd have to start by ensuring that you're installing the same versions of postgres and postgis as on the RDS, and then see if the dump you create works. If the errors in the log ring a bell, please help in clarifying them. I am a little bit at my wit's end on how to go about this, so i could really use some fresh perspective/ideas.

**Comment by xamanu** [comment]
Thanks for the detailed description and going that far.

Looking at the errors there seems to be a permission issue before any version mismatch, but this needs some deeper looking into it.
