### ISSUE TITLE
Implement new project cards

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1628]
Improve the project cards on the contribute/explore page and appear as recommendations in other parts of the application.

Design reference: https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/353854508

**Comment by thadk** [comment]
@xamanu @hexiaok  I noticed the final design does not show the Feature/Popular label above and to the left of the card in any of its examples. Is this still called for?

**Comment by willemarcel** [comment]
@ramyaragupathy @JorgeMartinezG In the new frontend, the projects cards needs to show the `lastUpdated` date, but it's not on the `/project/search` endpoint yet. Could you add it?

**Comment by thadk** [comment]
Thanks @JorgeMartinezG! Here are the fields I hope to connect to for this issue and https://github.com/hotosm/tasking-manager/issues/1639 . Any further help or pointers very welcome :

- [ ] Can you confirm that "lastUpdated" is the same as "last contribution by users"? 
- [ ] When the number of contributions is large, the design recommends using "number of contributions" instead of "last contribution by users" date/time. Is this available somewhere already?
- [ ] The other question I had was about how to query the search API for "featured" projects. (I think the idea of "popular projects" was removed from the design?)
- [ ] Is there a country-of-project field anywhere? The design calls for a relatively short filterable country/location name (Mozambique; Colombia; DRC) as both a query parameter and as data on the project. I'd be happy to help generate this field if there is nothing like it yet using a spatial join & natural earth data on some sort of data dump.
- [ ] The design calls for "total mappers" but I only see "active mappers" in the API – do we think this is okay?
- [ ] the "dueDate" field, rarely used, which is currently only on the project detail/summary endpoint, should maybe be in the project search as well.

**Comment by willemarcel** [comment]
@thadk yes for the first topic, I confirmed it.
- About the country information, there is a PR https://github.com/hotosm/tasking-manager/pull/1751 
- About the campaign/mapping type, I think there is already a PR https://github.com/hotosm/tasking-manager/pull/1762
- Yes, the dueDate should be in the `search` endpoint.

**Comment by JorgeMartinezG** [comment]
@thadk To include more information:

  **When the number of contributions is large, the design recommends using "number of contributions" instead of "last contribution by users" date/time. Is this available somewhere already? I only see "active mappers" in the API – do we think this is okay?**

There is also a PR which checks the number of contributions per day of a project https://github.com/hotosm/tasking-manager/pull/1768

  **The other question I had was about how to query the search API for "featured" projects. (I think the idea of "popular projects" was removed from the design?)**

What do you mean with _featured_ Like recommended or favorites?

  **The design calls for a project type field that is not the campaign or mapping type: "Public Health"; "Refugee Response"; "Disaster Response" are examples. Is there a place to find these yet? (As far as I can tell, they are not yet used elsewhere on the interface as filters, except to display in the card.)**

This is related to the **Interests** feature, to associate interests with projects and users . I am currently working on this and expect to create a PR this week.

  **the "dueDate" field, rarely used, which is currently only on the project detail/summary endpoint, should maybe be in the project search as well.**
Checking the source code, the project search does not return the due_date field. I can create a new Pr including this field. cc @willemarcel

**Comment by thadk** [comment]
> What do you mean with featured Like recommended or favorites?
On the home page of the new design there are about 5-10 featured projects. Maybe @xamanu can help us understand how this will be managed.

**Comment by xamanu** [comment]
Indeed featured project is a new functionality and we need an issue for this. I think this is just the possibility for admins (not PMs) to highlight certain projects as "featured". This could be either done inside the project editing page, but only visible for admins (not PMs) or on a separate settings page to add and remove projects as featured. @russdeffner most likely can give some more thoughts and input on that.

**Comment by JorgeMartinezG** [comment]
@xamanu Do you think we can make use the **Favorites** db model? I mean, featured projects could be projects favorited by an admin.

**Comment by xamanu** [comment]
I see them quite different. Favorited is a personal thing. And featured projects direct the list for all. Admins can also be mappers that fav their beloved projects. And we would run into new issues on how to maintain the list if certain admins fav different projects and other want to unfav them.

A simple checkbox on a project, only visible to admins seems to me the easiest and still comprehensible implementation.

**Comment by thadk** [comment]
@JorgeMartinezG Building on @xamanu's last comment, do you think that a new field would be possible and reasonable to add to the backend? It would be shown as a checkbox on the project admin and only shown to site administrators. 

We would just need it to be query-able in the search API endpoint.

**Comment by thadk** [comment]
@JorgeMartinezG I presume that old projects will not get any Interest entries, so just leave it off if it is empty? 

Also I noticed the new `campaign`(s) field is no longer `campaign_tags`– can that contain multiple campaigns sometimes?

**Comment by thadk** [comment]
We merged the first version of this with https://github.com/hotosm/tasking-manager/pull/1819 

Still waiting for an API for the featured projects.
