### ISSUE TITLE
Implement redesign of the user profile page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#1641]
A user view that will show stats, badges, contributor timeline, contributions map and some charts.

Design reference: https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652191

Depends on #1617, #1640 and #1604.

**Comment by thadk** [comment]
For the Contribution Timeline calendar piece, I recommend using an approach like this example does to wrap the d3 calendar into React with the @vx/Group component:
https://codesandbox.io/s/p5lz8vv49q
via: https://github.com/hshoff/vx/issues/191

For the donut/pie charts, I recommend continuing to use the @semiotic wrapper of D3 that was used by the project detail page. This should be lazy-loaded using React Suspense in a similar way as https://github.com/hotosm/tasking-manager/pull/1868 so that it does not grow the bundle for the whole site.
https://semiotic.nteract.io/guides/pie-chart#donut-chart
