### ISSUE TITLE
Email design template

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1675]
The current emails are pain text but should look nice:

![image](https://user-images.githubusercontent.com/97706/58959316-560b4700-8794-11e9-879b-5bda7f5a5a21.png)

This is a follow up to #1377 and #1378 and fits into the redesign work.

**Comment by willemarcel** [comment]
Other improvements we could do on this:

- [ ] use different subjects like "New comment on project X" or "New message from user X" to avoid the email client from hiding the content of the new emails because it's equal or similar to the previous one
- [ ] show the content of the notification on the email body
- [ ] set a name like "{ORG_CODE} Tasking Manager' instead of only the email address (currently it is `noreply@hotosmmail.org`. So the user will recognize and trust more our messages.
