### ISSUE TITLE
Project Dashboard - validation stats missing in contributions section

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#1685]
Flagged by a contributor on slack:
> There might be a bug in reporting mapped/validating numbers in TM3 dashboard. under tab 'contributions' I seen no records updated of validated tasks by myself. See project 5136  On my Profile page 'Frans S' it says 101 tasks validated.  On the Project dashboard : nothing.

**Comment by xamanu** [comment]
More examples of projects with this issue:

* https://tasks.hotosm.org/project/5972
* https://tasks.hotosm.org/project/6128

**Comment by RAytoun** [comment]
Hi Ramya, How is this progressing? I know you are all very busy at the moment. If it is any help I do notice that if the validator has completed some mapping tasks then there are validator sttatistics shown as well. If the validator has got 0 completed mapping tasks then they do not appear in the stats even if they have validated a load of tasks.

**Comment by RAytoun** [comment]
Hi Ramya, The problem is still there.  A random selection of past projects and present projects does not show any change to the incomplete validation counts. #5824 is 100% validated but shows 1573 task squares mapped and only 820 validated https://tasks.hotosm.org/project/5824/dashboard : #5923 is 100% validated but shows 292 mapped and only 1 validated https://tasks.hotosm.org/project/5923/dashboard : #6073 is 100% validated but shows 76 mapped and 0 validated https://tasks.hotosm.org/project/6073/dashboard

**Comment by RAytoun** [comment]
The problem still seems to be with the validation count where the validator has not mapped any task squares on that project so there is no entry for them. You will see at the bottom of the list under contributions.... the list of contributions stops at contributors who have mapped only 1 task and does not go to contributors that have mapped 0 tasks but have validated tasks.

**Comment by ramyaragupathy** [comment]
hey @RAytoun - sorry missed your comment notifications. This is fixed and is available for testing on staging instance. Soon this will go live.

**Comment by RAytoun** [comment]
Thanks @ramyaragupathy I saw that in the staging version and have noted  it. It will be great to have those stats back again. Thank you for spending your time and expertise on this. Greatly appreciated.
