### ISSUE TITLE
Order of language selection

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1746]
Feedback provided in direct messages:

> It seems as the list of languages isn't consistently using the same rule for deciding ordering.
>
> Examples:
> * Suomi is listed before Francais, guessing because Suomi is Finnish.
> * Persian is listed before Suomi, guessing because Persian is Farsi
> * but Bokmal is listed before Nederlands. Bokmal is Norsk or Norwegian. Maybe it should go after Nederlands?  
> * Also maybe it should be listed as Norsk (Bokmal), so one day when Norsk (Nynorsk) gets added they will be next to each other.
> * also: For Chinese and Korean, the name is in the languages font.  Makes sense, if that's the only language you know (and is respectful). But  Persian (Iran)  isn't done that way.
> * Chinese is listed at the bottom of the list, probably because it uses Zhongwen.

This issue is to review the list and propose a consistent order and system for naming.

**Comment by xamanu** [comment]
[This list on Wikipedia](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) might be useful. Compare the column "ISO Language name" and "Endonym".

**Comment by wireguy** [comment]
Take a look at Thunderbird's language selector at the bottom right of the website: https://www.thunderbird.net/en-US/

It seems to be the most complete example of a web page with language selector.

Also note that not all languages start with a uppercase letter (magyar for example)

**Comment by verdy-p** [comment]
Wikimedia commons already orders its many languages consistantly in its top
navboxes, they are ordered by their native name, first by script then by
the default alphabetic order of each script, grouping all rtl scripts after
ltr scripts

**Comment by wireguy** [comment]
So Wikimedia and Thunderbird use the same ordering, the 4th column in  [639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).

Using that ordering, TM isn't bad, only 2 are out of order.  Galician (gl) should be before Magyar (hu).

Language names:
For the most part Wikimedia and Thunderbird use the Endonym from the table on [639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)  
The only one I noticed that was different was Lithuanian. 
Wiki table uses lietuvių kalba, but web pages use lietuvių, TM uses Lietuvos.

Of the 30 Language names that TM uses, 11 are correct, but
9 use a different name from the endonym table (ar cs fa gl id lt nb pl pt-br)
10 use a different letter casing from the endonym table (da es fi fr hu it pt ru sl vi)

**Comment by verdy-p** [comment]
Sorting language *names* (especially when they are presented as their
native names) by language code is completely inconsistant (and notably when
only the language name is presented to the user and there's no visible
indication of the language code that the user can lookup visually).
If you present a list of language names (either in English or in another
single language, or in its own native name) you MUST sort it according to
this name.

Note that Alemanish should then be first in the list, before Afrikaans,
even if their code (gsw and af) are not ordered this way. And Albanian will
come before if the list presents language names in English, but not if it's
the native name (Shqip) which will still sort after "Serbian" (named in
English) but before "Srpski" (named in its native name with the Latin
script).

So be consistant: consider what is displayed and what users really want to
see first: these langauges are supposed to match a language that user can
read, and these names should then be in their native name and not their
names in English (that they may not read correctly to guess what is their
own language).

So the order and presentation used in Commons is the most user-friendly!
* Don't use language code at all
* present languages only with their preferred native name
* group languages names by script, grouping all LTR scripts before RTL
scripts, then sort scripts logically: alphabets (be careful of the language
names with dual script like Serbian which should be in a specific group
between the Latin and Cyrillic group, just after the Latin script),
abugidas, syllabaries, sinographic for the LTR part, and then RTL abjads.
* in each group, sort the language names by the locale-neutral default
order defined in UCA and CLDR (ignore differences of sorting for example in
Swedish for Ö sorting after Z instead of with O, because it makes no sense
in a multilingual list)

**Comment by willemarcel** [comment]
The current behaviour is consistent with most other websites.

**Comment by verdy-p** [comment]
"Most other websites" means nothing:

- if the list does not show any code but only English language names, then it must be sorted by these English names ; you may still append codes or autonyms *after* the displayed English name

- if the list does not show any code but only native language names (endonyms), then it must be sorted by these native names, grouped by their native writing direction and then by script ; as the list is then multilingual, the sort order must also be locale neutral. (the sort order used in Wikimedia Commons) ; you may still append codes or their english meaning *after* the displayed autonym.

- Only if the list starts by items showing codes (even if there's a precision added for what they mean), then you sort the list by codes; but you MUST show the codes first if you want to append the a precision: the English name, then the autonym (not the reverse because of bidi reordering)

Any other choice is inconsistant.
