### ISSUE TITLE
Login to OSM within popup or modal

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1892]
In order to improve user onboarding #1186 the redesign suggests to do the OpenStreetMap registration in a pop-up. Alternatively, if possible, an modal can be used, too.

![image](https://user-images.githubusercontent.com/97706/66125096-a1fcba00-e5d5-11e9-8133-ca7a9ae86248.png)

**Comment by JorgeMartinezG** [comment]
An update in this issue. The popup window should be created in the client side. Right now Tasking Manager performs the oauth authorization in the server side using flask-oauthlib. It would involve modifying the authorization workflow in tm, including the token verification, since the token which is used to check if an user is logged, is created by TM not OSM.

MapCampaigner https://github.com/hotosm/MapCampaigner/blob/develop/flask_project/campaign_manager/templates/new_base.html#L170

and ID editor
https://github.com/openstreetmap/iD/blob/09f97b086644b3052f87b5f011161046890058b6/modules/services/osm.js#L18

use the osmauth library written in Javascript.

Let me know your opinion @xamanu and @willemarcel

**Comment by JorgeMartinezG** [comment]
To make an update in this issue, work in progress is currently done within this branch:

https://github.com/hotosm/tasking-manager/tree/hotfix/1801-1914-popup-login

The api endpoints have been modified to return oauth params. The client now renders the login and consent in a popup window. The missing part is to generate the final auth token using the verifier got from OSM url. However, since there are two windows, storage and cookies are different. Need to pass the oauth_verifier from the login window to the parent one.

![image](https://user-images.githubusercontent.com/3285923/67491244-376df580-f63a-11e9-9b70-515b2762167b.png)

**Comment by willemarcel** [comment]
It's such a good news. Thanks, @JorgeMartinezG !
