### ISSUE TITLE
Share login with self-hosted iD

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#1910]
After supporting iD to be self-hosted (#1909) in a next step it is good to reduce the logins needed to get started with mapping in order to provide a seamingless experience to the users.

After logging into the Tasking Manager a user should be able to start mapping on the embedded iD without the need to login the editor again.

**Comment by xamanu** [comment]
As a first idea it came up to share the oauth key received through the Tasking Manager login with the self-hosted iD through private channels (e.g. docker network).

**Comment by xamanu** [comment]
Some more information on this idea:

> TM can do similar to what osm.org does:
> - Task manager becomes the main site and stores the users secrets however it needs to
> - iD runs in an iframe and TM passes the credentials to iD through the iframe.  Javascript code that starts iD already has the credentials.
> 
> Here is the code for osm.org. It’s Rails but the TM code would be similar.
> * [This renders the iframe and passes the credentials and other stuff as a data attribute](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/site/_id.html.erb)
> * [This renders the iframe contents](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/site/id.html.erb) (it’s just a div and some scripts)]:
> * [This is the javascript which starts iD, preauthenticates it, and puts it into that div](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/id.js)
> 
> That’s why users on osm.org don’t need to login to iD separately.  The Task Manager can do it that way too.

**Comment by xamanu** [comment]
I know there has been significant progress here. @JorgeMartinezG can you please share the status?

**Comment by JorgeMartinezG** [comment]
**Update:** In order to use Tasking Manager oauth credentials in id, we must pass to the frontend from the server (oauth consumers and tokens) the required keys to be rendered within the react component. The component must have iD embedded and call the preauth option when the it is mounted: https://github.com/openstreetmap/iD/blob/7b7a42cf762be970252a712044f4aedaa1bdb756/modules/core/context.js#L99

**Note:** For now, in this branch https://github.com/hotosm/tasking-manager/commit/12ee81c27cca905c7e3f1e6d2e5acc24523ff983 id is served as a static folder

**Comment by xamanu** [comment]
This looks good so far. We are implementing other parts on iD in the meantime. This can be closed.
