### ISSUE TITLE
Check list endpoints to not return 404 errors

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2047]
Some endpoints like, `/api/v2/projects/{project_id}/comments/`, `/api/v2/projects/{project_id}/annotations/` are returning 404 errors if there aren't, respectively, comments and annotations.

These endpoints should return 404 code only if the project doesn't exist. If there aren't entries of the entities that should be listed, the result should contain an empty array and a 200 status code. The same is happening in some other list endpoints.

**Comment by fitoria** [comment]
[WIP here ](https://github.com/hotosm/tasking-manager/pull/2084)

**Comment by joaovitor3** [comment]
Can I work on this issue?

I've already merged the work done by @fitoria in this [branch](https://github.com/hotosm/tasking-manager/tree/bugfix/return-values-fixes) and I believe there are missing fixes in the endpoints of `comments` and `contributions`, as reviewed in this [Pull Request](https://github.com/hotosm/tasking-manager/pull/2084).

**Comment by willemarcel** [comment]
@joaovitor3 yes, I've assigned it to you. Let us know if you need some help.

**Comment by joaovitor3** [comment]
Thanks, @willemarcel!

Following the work done by @fitoria, I've added this if statement in the `ProjectsContributionsAPI` class in the `/server/api/contributions.py` file

```py
class ProjectsContributionsAPI(Resource):
    def get(self, project_id)
        if not ProjectService.exists(project_id):
            return {"Error": "Project not found"}, 404
```

And the same for the  `ProjectsActivitiesAPI` class in the `/server/api/contributions.py` file.

```py
class ProjectsActivitiesAPI(Resource):
    def get(self, project_id):
        if not ProjectService.exists(project_id):
            return {"Error": "Project not found"}, 404
```

In the `Activities` problem, I also removed a raised Exception from the `get_latest_activity` method located in the `StatsService`  class, due to this exception treatment returns a 404 status code in the `ProjectsActivitiesAPI` class.

https://github.com/hotosm/tasking-manager/blob/4ff9c4c1653b8c3f2b6024b8867f9dcb0b71e840/server/services/stats_service.py#L113-L135

Also, I thought that the Exception `Not Found` found in both `ProjectsContributionsAPI`, `ProjectsActivitiesAPI` classes should be removed, as this part of the code will be unreachable

https://github.com/hotosm/tasking-manager/blob/4ff9c4c1653b8c3f2b6024b8867f9dcb0b71e840/server/api/projects/activities.py#L37-L38

https://github.com/hotosm/tasking-manager/blob/4ff9c4c1653b8c3f2b6024b8867f9dcb0b71e840/server/api/projects/contributions.py#L34-L35

The endpoints for `annotations` and `comments` seem to be working fine in the `bugfix/return-values-fixes` branch.
I would like to know if this is respecting the architecture and if it's ready to open a Pull Request.

**Comment by willemarcel** [comment]
@joaovitor3 it seems good, please open a PR! Thank you very much!

**Comment by joaovitor3** [comment]
I opened a PR [here](https://github.com/hotosm/tasking-manager/pull/2327), but I believe there were many changes in the source, and rebasing doesn't solve all issues as lower case variables and stylesheet problems. Besides because of merging there were 18 files changed.

Could I close this and open a new one from the actual `develop` branch?
