### ISSUE TITLE
Fix query for touched projects

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2094]
The endpoint `/api/v2/projects/queries/{username}/touched/` is not returning the correct results. I have tried with two different users and it was missing some projects on the results.

**Comment by ramyaragupathy** [comment]
For touched projects endpoint:
* values are picked from `projects_mapped` field in users table
* `projects_mapped` column only includes mapped and validated projects. Projects where user has locked a task but did not do any state change or where mapper left a comment on a task are not considered for `projects_mapped` field

This endpoint is a replacement for `/api/v1/user/{username}/mapped-projects` - so it ony makes sense to return where mapper has validated/mapped - per discussion in our [API changes spreadsheets](https://docs.google.com/spreadsheets/d/1aiR07_Irdf_cLaSEf3iO84iVkAdYaSxDR9J2FeWvGBA/edit#gid=0) let's have it as a query parameter on `/api/v2/projects?touched={user_id}`

cc @willemarcel @xamanu 





but we should have it renamed to /api/v2/projects/queries/{username}/mapped instead of /api/v2/projects/queries/{username}/touched





/api/v2/projects/queries/{username}/touched should return all projects that user has interacted with





this could be a new endpoint
