### ISSUE TITLE
Change default value for user's default_editor

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2109]
Across the system we use the values `[ID, JOSM, POTLATCH_2, FIELD_PAPERS]`, but on the User model the default value has the `i` in lowercase. Replace it with `ID` to keep the consistency.

`default_editor = db.Column(db.String, default="iD", nullable=False)`

**Comment by ramyaragupathy** [comment]
Per discussion w/ @wille -
* Default editor was introduced in TM4 for the user table
* `default_editor` column defaults to `iD`
* We have a [list of editors](https://github.com/hotosm/tasking-manager/blob/master/server/models/postgis/statuses.py#L79) in our codebase where we mention `ID` editor

Since this is still not available on  master we could:
 *  Update the default value to `ID` in [user model](https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/user.py#L57)
 *  Modify the [migration file](https://github.com/hotosm/tasking-manager/blob/develop/migrations/versions/6612e4d6524c_.py) to populate default values with right case

**Comment by willemarcel** [comment]
Started working on it with https://github.com/hotosm/tasking-manager/pull/2146
It needs some backend changes yet

**Comment by willemarcel** [comment]
I created a follow up issue specific to the backend change needed https://github.com/hotosm/tasking-manager/issues/2240
