### ISSUE TITLE
Fix project search by status

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2132]
I tried to fetch `/api/v2/projects/?projectStatuses=DRAFT` and also with `ARCHIVED`, but it didn't filter the projects.

When receiving an invalid status value, it should return an empty array not a 500 error.

**Comment by willemarcel** [comment]
@ramyaragupathy detailed that the DRAFT and ARCHIVED filters are including also the PUBLISHED projects. I suggest to restrict the results to the statuses present in the query.

**Comment by joaovitor3** [comment]
Thanks for the quick response @willemarcel, I will look at these two issues.

About being a new contributor, I would like to enter the HOT slack chat as mentioned in the [working groups section](https://github.com/hotosm/tasking-manager/blob/develop/docs/working-groups.md), but after answering the form and receiving the link to access the channel, the [invitation link](https://hotosm.slack.com/join/shared_invite/enQtNDkyMDA4MjQ1MDEyLWNmMjU4ZmEyNzI5MTc2MmJkODU5ZTA0ZmFhYWMwZmYyZjdhYThkMTI2OWJjNDZmMTlhMjBlYzYwMjdmYjNjZDg) does not seem to be active.

Am I doing something wrong? If not, should I open an issue about it?
Thanks for the feedback

**Comment by joaovitor3** [comment]
Can i work on this issue?

**Comment by willemarcel** [comment]
@joaovitor3 yes, I assigned it for you

**Comment by joaovitor3** [comment]
Thanks
As soon as I finish I will open a pull request

**Comment by joaovitor3** [comment]
I made a little progress on this. 

I find out that this `filter projects` method always started with a value for a `PUBLISHED` project, maybe that's why the `DRAFT` and `ARCHIVED` filters were including also the `PUBLISHED` projects:
https://github.com/hotosm/tasking-manager/blob/bfc609c0cf6ae639f7c0e5ebae128aa9a4594627/server/services/project_search_service.py#L194-L199

I thought to start this array without data and then add an else statement in case there's no `projectStatuses` in the request. I guess this solved the `ARCHIVED` project problem, but I still stuck in the `DRAFT` projects problem. I believe this is a problem related to the Project Manager role permissions, as shown in this snipped:

https://github.com/hotosm/tasking-manager/blob/bfc609c0cf6ae639f7c0e5ebae128aa9a4594627/server/services/project_search_service.py#L200-L203

The code looked like this:

```py
project_status_array = []
if search_dto.project_statuses:
    for project_status in search_dto.project_statuses:
        project_status_array.append(ProjectStatus[project_status].value)
    else:
        project_status_array = [ProjectStatus.PUBLISHED.value]
```

I can open an Pull Request with an WIP tag for better communication and code corrections.

**Comment by willemarcel** [comment]
@joaovitor3, great work!

About the `DRAFT`, I believe that part of the code is avoiding users that are not `PROJECT_MANAGER` or `ADMIN` from seeing `DRAFT` projects. That is a desired behaviour.

I like the solution you proposed! It would be good if you could also enable to filter by more than one status, receiving an argument like `projectStatuses=ARCHIVED,PUBLISHED`

**Comment by joaovitor3** [comment]
@willemarcel Thanks for the feedback!

I guess currently the endpoint `/api/v2/projects` already enable the status filter for one or more projects. This is done in this part of the code, that iterate through all statuses and `append` then to the `project_status_array` variable.

https://github.com/hotosm/tasking-manager/blob/bfc609c0cf6ae639f7c0e5ebae128aa9a4594627/server/services/project_search_service.py#L196-L199

I tested the request with these arguments `/api/v2/projects?projectStatuses=ARCHIVED,PUBLISHED` and the filter worked as expected for both `DRAFT` and `ARCHIVED`.

If everything is alright can I open an Pull Request?

**Comment by willemarcel** [comment]
@joaovitor3 sure, please open a PR!

**Comment by joaovitor3** [comment]
@willemarcel
Just opened the [Pull Request](https://github.com/hotosm/tasking-manager/pull/2315)
