### ISSUE TITLE
Task user history bug

### ISSUE THREAD

**Issue by maxgrossman** [hotosm/tasking-manager#2320]
I was at a mapathon at George Washington this week and the student mapping group asked about a bug they are coming across in project 2742.

They have 2 tasks not yet validated.
When you select validate for these tasks, there is no user history and a ui element appears saying there was a server error.

Looking at network logs, `https://tasks.hotosm.org/api/v1/project/2742/mapped-tasks-by-user` replies a 404.

Here's one of the task urls.
https://tasks.hotosm.org/project/2742?task=782#bottom

**Comment by ramyaragupathy** [comment]
Hey @maxgrossman - thanks for flagging the issue in the repo. I got to debug the issue a bit and here are my notes so far:

* Tasks 784 and 788 are the problematic ones in Project 2742
* 784 and 788 seems to have no task history at all 
* Since there is no task history so they are supposed to be only in ready to map state, however for 784 and 788 show up as mapped.

While I don't have an immediate answer on what might have led to this state change, as an immediate step I have reset the task state as READY TO MAP since there is no task history recorded so far. So now users can pick this task for mapping and then later validate.

**Comment by ramyaragupathy** [comment]
On https://tasks.hotosm.org/api/v1/project/2742/mapped-tasks-by-user returning 404 - that's a bug -  the current logged in user does not have any task locked, so the result is null. Instead of a 200, backend handles this as a 404 response because of null value. We're dealing this better  in the upcoming release.

**Comment by xamanu** [comment]
@ramyaragupathy can you check if this has been addressed in TM4?

**Comment by xamanu** [comment]
This still needs our attention. Moved to the roadmap.

**Comment by xamanu** [comment]
This has been fixed within #2775 and is going to be part of TM4
