### ISSUE TITLE
JOSM validation plugin

### ISSUE THREAD

**Issue by d3netxer** [hotosm/tasking-manager#235]
This JOSM plugin could let you import all of the squares for a project into JOSM (as a new layer maybe). Then the validator could validate multiple squares at once. For each square they could select it in JOSM and check it they want to mark it as validated or not. They could also input notes. This information can then be synced back to the TM when the user decides.

**Comment by bgirardot-np** [comment]
We are working toward something like this. Initial release this happens outside of the Tasking Manager as a downloadable gpx file to open in JOSM.

Other thing that complicates the process is what to do with locked tasks, would the validator still get data for those tasks? Could lead to conflicts.

I think that second point is solved.

The first point needs to either have the gpx translated to JOSM's flavor of OSM XML or just generate that OSM XML instead, which JOSM's Remote Control api can then accept.

**Comment by bgirardot** [comment]
@d3netxer I think we covered this in the current release of the TM3. You can select by user or by area or one at a time like now.

You do have to download the data manually in JOSM when selecting multiple tasks because of the risk of downloading large amounts of data because JOSM only accepts a bounding box for a layer to download data.

I am going to close this one and if you could please have a look at the staging site for validation and see if it comes close enough to your original suggestion.

http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/

cheers
blake
