### ISSUE TITLE
TM on headless machine

### ISSUE THREAD

**Issue by cascafico** [hotosm/tasking-manager#2420]
I installed docker-compose version on a LAN headless machine (192.168.1.9) debian 10. I cannot authenticate OSM since landing page is unreachable:

CASE 1, TM_APP_BASE_URL=http://127.0.0.1:5000
http://127.0.0.1:5000/api/v1/auth/oauth-callback?redirect_to=/&oauth_token=<token>&oauth_verifier=<verifier>

CASE 2, TM_APP_BASE_URL=http://192.168.1.9:5000

http://127.0.0.1:3000/authorized?username=Cascafico&session_token=<token>&ng=0&redirect_to=/

Where 127.0.0.1:3000 comes from? How can I configure tasking-manager.env ?
Have I to install and run TM only on a 127.0.0.1 localhost desktop machine with browser?

**Comment by willemarcel** [comment]
@cascafico are you using `master` or `develop` branch?

**Comment by cascafico** [comment]
> @cascafico are you using `master` or `develop` branch?
git clone https://github.com/hotosm/tasking-manager.git

**Comment by willemarcel** [comment]
@cascafico So it's the develop branch, on that case the api available is the v2. I'm not using the docker setup. but I believe the docker script builds the frontend and serves it on the 5000 port.

Have you seen the `example.env` file? You can also configure the project with env vars, instead of adding the `tasking-manager.env`.

**Comment by bopercival-hot** [comment]
No responses, question closed
