### ISSUE TITLE
Solve create-react-app in a cloud deployment

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2445]
When testing TM4 on a mapathon the following problem has been detected: A subset of users received a whitescreen, either directly after authentication of when browsing to a project. The error was identified as `GET https://tm4.hotosm.org/static/js/6.da8f26eb.chunk.js net::ERR_ABORTED 404`.

@willemarcel has suggested two possible approaches to solve this:

> * Serve it from S3 instead of having a flask view: https://medium.com/@wolovim/deploying-create-react-app-to-s3-or-cloudfront-48dae4ce0af
> * Push the frontend release build to a GitHub Branch or a S3 bucket on the build pipeline, download it when deploying new instances and use the build instead of building it before starting the server

**Comment by dakotabenjamin** [comment]
Thinking about the infrastructure/deployment needs for either option- 

Option 1:
- [ ] New CloudFormation Components
    - [ ] S3 Bucket
    - [ ] CloudFront Distribution
    - [ ] Route53 Record for Load Balancer (optional)
- [ ] Edit Autoscaling LaunchConfig to not serve frontend
- [ ] Edit Environment Variables to set API URI
- [ ] During CircleCI Deployment, build frontend and push to s3 bucket
- [ ] Create logic so that updates to frontend don't affect infrastructure

Option 2: 

- [ ] Cloudformation Component: s3 bucket
- [ ] In LaunchConfiguration, download frontend build instead of building locally
- [ ] Build frontend in CircleCI and push to s3

Option 2 is a little tricky because we need to ensure that files are not tampered with on s3 or else we might end up with multiple servers with conflicting frontend builds.

**Comment by willemarcel** [comment]
> Option 2 is a little tricky because we need to ensure that files are not tampered with on s3 or else we might end up with multiple servers with conflicting frontend builds.

@dakotabenjamin Not sure if I understood correctly... I think we can start versioning the frontend on `package.json` file, so we could push the build to a folder with the same name as the version. That way we assure that we will download the correct version.

**Comment by dakotabenjamin** [comment]
Using https://github.com/hotosm/tasking-manager/tree/fix/create-react-app-deployment to make changes, I've completed the cloudformation and circleci components. 

You can find the frontend build here: https://d1qxwg0plztens.cloudfront.net/. When in production, this will be aliased by `tasks.hotosm.org` 

@willemarcel now we need to update environment variables to have communication with the API. In this case, `https://tasking-manager-react-app-582946328.us-east-1.elb.amazonaws.com/api/v2/projects/`. Is this an acceptable endpoint? I think I can make a route53 record to alias that as well if it makes it easier.

**Comment by willemarcel** [comment]
@dakotabenjamin we can set the API with the public URL tm4.hotosm.org or tasks-stage.hotosm.org
