### ISSUE TITLE
Check if task is already open in another browser tab

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2467]
Every time you use the ‘Resume mapping’ button, it loads the task as a new layer.
Consider changing to not allow task to be opened if it showing as locked but to give warning message instead and allow user to update EDIT STATUS and Submit to clear the lock. This would alert user that they already have task opened in editor.

**Comment by willemarcel** [comment]
@xamanu It should work that way, because I compose the window name using the project and task ids, but I don't know why it fails. Reference: https://developer.mozilla.org/en-US/docs/Web/API/Window/open

I think it'll be deprecated when we integrate iD editor, so I think it's not worth working on that.

**Comment by xamanu** [comment]
Agreed. Thanks.
