### ISSUE TITLE
Comment is created but not updated on frontend.

### ISSUE THREAD

**Issue by ritvikjain99** [hotosm/tasking-manager#2487]
If you comment on a project the comment is not rendered on frontend immediately but with the second comment you do after it.

![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/34532173/76409384-4e786e80-63b4-11ea-9bb7-cac2fe1be443.gif)

**Comment by xamanu** [comment]
Similar caching problems on the tasks page with the status not being updated immediately.

**Comment by ritvikjain99** [comment]
@xamanu the problem with status, I already tried to solve in #2602 .

**Comment by JorgeMartinezG** [comment]
@ritvikjain99 but the PR that you referenced does not have relationship with the api call used within project chat service in the backend. You can validate that is cache problem because once you post two or three comments in a row, you get same api response for each call.

the TTL is set to 10 seconds. This is why you get the results in the record created in this issue. I made a PR of this

**Comment by ritvikjain99** [comment]
@JorgeMartinezG yeah I completely agree, I was referring to this comment, sorry I forgot to mention !

> Similar caching problems on the tasks page with the status not being updated immediately.
