### ISSUE TITLE
Project favorites filter

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#2593]
`projects/?favoritedByMe=true` filter should return results based on auth token. However, at present, this filter is returning all projects in published state.

**Comment by joaovitor3** [comment]
I believe I find the problem. The `filter_project` (that is called for the `search_projects to return the projects filtered`) method always set the project status to `PUBLISHED` when receives None as `project_status` parameter in the `search_dto` and the favorited by query is below the status filter, which caused some strange things, I will give an example because I think that's the best way to explain this.

https://github.com/hotosm/tasking-manager/blob/42d000726247791bcfc9f619f80421a27c13a084/backend/services/project_search_service.py#L197-L227

Project 1 has the Status DRAFT and was favorited by me
Project 2 has the Status PUBLISHED and was not favorited by me
Project 3 has the Status PUBLISHED and was not favorited by me

The `/projects/?favoritedByMe=true` set the `project_status` array to `[1]` (the status for published), and in the line 211 this was filtered. When the code reaches line 220 for filter by `favorited_by_me` the query object has only projects with different statuses.

My solution was to add a new `project_array_status` in the `favorited_by_me` if statement (and keep the one of line 197) and query by `status` only after this part of the code.

My solution
```py
project_status_array = []
if search_dto.project_statuses:
    for project_status in search_dto.project_statuses:
        project_status_array.append(ProjectStatus[project_status].value)
else:
    project_status_array = [ProjectStatus.PUBLISHED.value]
if not search_dto.is_project_manager:
    project_status_array = list(
        filter(lambda x: x != ProjectStatus.DRAFT.value, project_status_array)
    )
# Removed the status filter

if search_dto.favorited_by:
    user = UserService.get_user_by_id(search_dto.favorited_by)
    projects_favorited = user.favorites
    if projects_favorited:
        query = query.filter(
            Project.id.in_([project.id for project in projects_favorited])
        )
        project_status_array = [project.status for project in projects_favorited]
        if not search_dto.is_project_manager:
            project_status_array = list(
                filter(lambda x: x != ProjectStatus.DRAFT.value, project_status_array)
            )
# Added the status filter
query = query.filter(Project.status.in_(project_status_array))
```

I don't know if that's the best solution in terms of performance, but that's what I thought for the problem

**Comment by ramyaragupathy** [comment]
Have user favorited projects?|Token on `/projects`?|search filter|current result|expected result
-----------------------------|----------------------|-------------|--------------|---------------
No projects favorited|yes|favoritedByMe=true|retruns all published projects|should return an empty array
No projects favorited|yes| favoritedByMe=false|retruns all published projects|return all published projects

Those were the two cases that I was checking while raising this issue.

@joaovitor3 - just removing the check `if projects_favorited`  will return empty results if the logged-in user does not have any favorite projects.  

`search_dto.favorited_by` attribute is populated with the user id only if there is an auth token supplied ( that is only if the user is logged in). So the filtering happens only if the user is logged in. Now when a user is logged in and there is ` favoritedByMe=true` ,  code fetches `projects_favorited` by the user. Suppose there is no project favorited , which is `projects_favorited=[]` then the logic does not flow to `query.filter` - thereby returning all projects in the results array. We should do`query.filter` irrespective of the value of `projects_favorited` so that we get empty results when there are no favorited projects.

In the existing code `search_dto.created_by` follows this logic, however `search_dto.mapped_by` and `search_dto.favorited_by` does the  `query.filter` only if  `projects_mapped`/`projects_favorited` is non-empty. Can you please remove this check for both `mapped` and `favorited` projects?

**Comment by joaovitor3** [comment]
I can do this!
Just checking if I get it.
Removing the `if projects_favorited` will solve the problem for logged in users, right?

Another question
When the filter `favoritedByMe=true` is present, but without authentication, the code always raises an Exception when the `verify_token` is called that has just a `pass` for treatment.

https://github.com/hotosm/tasking-manager/blob/00e0a19c6d2c4cf73bc9d522099256390dc94e06/backend/api/projects/resources.py#L491-L505

This is working as expected?
