### ISSUE TITLE
Migrate campaign tags to entities

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2612]

**Comment by Nikitag0329IITkgp** [comment]
Can I work on this? If yes can you explain it further?

**Comment by ramyaragupathy** [comment]
Hi Nikita - thanks for your interest, I have been working on this project for a release rollout in a week, but missed updating status here. Sorry about that. This issue is related to a DB upgrade in our application. We handle all our [DB updates](https://github.com/hotosm/tasking-manager/tree/develop/migrations/versions) through alembic. You can learn more about the process here: https://alembic.sqlalchemy.org/en/latest/tutorial.html

**Comment by ramyaragupathy** [comment]
Implemented through https://github.com/hotosm/tasking-manager/pull/2668
