### ISSUE TITLE
Project creation geometry problems

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2653]
A user reports:  When creating a project on TM4 and uploading the geojson (`UNSOSwaterwaysProject01Area.geojson`) or osm file (`UNSOSwaterwaysProject01Area.osm`) in the first step it shows well the geometry:

![01shapeok](https://user-images.githubusercontent.com/97706/78586848-99f33080-782b-11ea-95d7-5b7302b3d3b5.png)

But zooming in shows problems:

![02shapewrong](https://user-images.githubusercontent.com/97706/78586851-9b245d80-782b-11ea-899f-25c96aa97f26.png)

After adding a tag (leisure=park) to the area of interest (`UNSOSwaterwaysProject01Area2.osm`), weird behaviour stops.

Example files to reproduce the problem: [issue-2653-example-files.zip](https://github.com/hotosm/tasking-manager/files/4439897/issue-2653-example-files.zip)

**Comment by JorgeMartinezG** [comment]
Yes. Problem replicated locally

The reason of this issue is related to the geometry type. Both geojson and osm files have LineString as geometry type. It was not handled by TM. Also, it was not possible to compute the area of a LineString, making the user pass from step 1 to step 2 (create taskGrid). Also, the aoi sent has more than 5000 km^2

PR  #2684, validates  the geometry and transforms a closed linestring geom to polygon.
