### ISSUE TITLE
Set cronjob for regular operations

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2789]
Follow up to https://github.com/hotosm/tasking-manager/issues/2108 and https://github.com/hotosm/tasking-manager/pull/2781 we need to prepare the infrastructure to run such a cronjob.

**Comment by joaovitor3** [comment]
Maybe this could be done with celery.
As in the future, there's a chance of this need as said in this [issue](https://github.com/hotosm/tasking-manager/issues/2786). 
It is more complex than the current cronjob configuration because it would be necessary to add a broker (RabbitMQ, Redis, etc) and some configuration, but would bring a lot of benefits like monitoring and management when many tasks are performed.

**Comment by dakotabenjamin** [comment]
It looks like we are using python's APScheduler to perform these tasks- I do not think any more work is needed here.

**Comment by bopercival-hot** [comment]
closed
