### ISSUE TITLE
Project creation: see existing projects in the area

### ISSUE THREAD

**Issue by xamanu** [hotosm/tasking-manager#2877]
In TM3 there was the functionality to toggle the view on project creation to display existing projects in the region one was drawing and creating a new project area. Please bring it back.

**Comment by russdeffner** [comment]
I would add that it isn’t ideal in TM3 though. In the case there is just one existing project in the area, works fine. However if there are multiple it breaks down fairly quickly. Example - if someone has already created a roads project and a separate buildings project in the same location (which we often do) then if you go to click on them to find out project number or more information you can only ever click the one sitting on top. Nice idea, did not function as well as it could. Please improve if we are to spend time bringing it back.

**Comment by willemarcel** [comment]
Details to check:
Other details to consider::
- Avoid downloading too much data
- Think about layer style to make it easy to understand

Endpoint that returns the data: `/api/v2/projects/queries/bbox/`

**Comment by russdeffner** [comment]
In light of the Tech WG meeting w/ Kontur, I think there are a few options to explore which could help resolve this issue:
1. Kontur already has the ability to add more TM instances to their layer showing existing projects, then it would be fairly straight-forward to bring that layer into the tasking manager as an optional background during project creation. The downside is that we may never be able to find all the existing TM instances out there and some may very well want to be 'private'/undiscovered/'turn-off' the ability to call projects via their API (not to mention instances that use versions too old to be called).
2. What may be a better option for many reasons (see also my previous comment about multiple projects occupying same space) is that Kontur has a layer that can be fine-tuned to show 'recent activity' which could be a better proxy than just 'are there previous projects' because even if there have been projects, they may be old enough that an update is necessary, and there may be activity happening (say in disaster response) outside of the TM that needs to be accounted for - i.e. the local community is already mapping and if you have a layer that would say 'hey, there's a lot of recent activity here, maybe you don't want to create a project without checking out what's already going on' - that may be more valuable then just HOT TM project boundaries.
