### ISSUE TITLE
Trim/Clip During project creation not working with imported AoI

### ISSUE THREAD

**Issue by bgirardot-np** [hotosm/tasking-manager#317]
When using the import AoI function, nothing happens on Step 4, Trim AoI. It does not matter if clip to AoI is selected or not.

**Comment by feenster** [comment]
I suspect this may be related to the AOI data you are using.  Can you send the data and I will take a look

**Comment by feenster** [comment]
Blake.  Thanks for providing the sample AOI data.  The geometry type of the data you provided Linestring.  TM3 is expecting AOI's to be polygons.  The AOi is being rejected because it is not a polygon.

**Comment by feenster** [comment]
I have improved the validation, error handling and messaging.  The user will now see an error message in the UI informing them that the AOI needs to be a valid MultiPolygon.

**Comment by bgirardot-np** [comment]
Hi Ian, 
Thank you for looking into this.
Could you improve the error message to say it is a LineString and needs to be a MultiPolygon?

If we know the issue is the aoi is a linestring, it would be good to say that, as just saying "it needs to be a valid MultiPolygon" is pretty generic, that doesn't help me very much, but if we say this is a linestring, well then I know what I need to fix.

**Comment by feenster** [comment]
I agree that would be better, however that would be a bit more involved.  The challenge is that the validation is taking place on the server.  However, because of translation we cannot use any error message text in the client that is generated on the server.  We would need to use a scheme where the server generates error codes and passes and them to the client, which then looks up translated error messages.

If you think this is a high priority, we could come up with a proposal for this.

**Comment by bgirardot** [comment]
I definitely think we should tell users right away if they are using a geojson that is not going to work. I am going to close this issue and create a new one that is specific to that issue.
