### ISSUE TITLE
Angular Translate - warning messages not translated

### ISSUE THREAD

**Issue by bgirardot-np** [hotosm/tasking-manager#345]
The warning messages in the create project workflow are not being translated, see attached images.
![2017-05-21_14h06_32](https://cloud.githubusercontent.com/assets/12796805/26283884/cb699c32-3e2f-11e7-9cfc-9f798364238e.png)

**Comment by bgirardot-np** [comment]
I should mention, this is locally, I will make a pr for these changes shortly.

**Comment by LindaAlblas** [comment]
This is because there are two HTML elements, a <p> and a <strong>

You can either remove the <strong> tags or translate the content of the <strong> tag separately.

<p>{{ 'Warning : Maximum number of tasks reached. If smaller tasks are required please make the area of interest smaller.' | translate }}</p>

<p><strong>{{ 'Warning' | translate }}:</strong>{{ 'Maximum number of tasks reached. If smaller tasks are required please make the area of interest smaller.' | translate }}</p>

**Comment by bgirardot-np** [comment]
I followed your advice Linda and just created strings to translate that do not include HTML. Turns out this is good for security anyway so hopefully it works out ok this way :)
