### ISSUE TITLE
Multiple Search Criteria on Manage Projects page

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#3829]
I don't see a way currently to search for "my archived projects" as Archived and Created by me are mutually exclusive on the filters.

**Comment by willemarcel** [comment]
Good suggestion. We could add a switch between "managed by me" and "created by me", and make it independent from the status filters.

**Comment by NatashaKSS** [comment]
Hi @willemarcel I think I can help on this issue! May I ask a few clarifying questions about the expected behaviour of the filters?

**Trial Implementation:**
I dug into the code at `./frontend/src/components/projects/myProjectNav.js` and saw that the filters have the following logic:

1. Click on "Active" filter button, shows "Active" projects that are "Managed by me" 
2. Click on "Draft" filter button, shows "Draft" projects that are "Managed by me" 
3. Click on "Archived" filter button, shows "Archived" projects that are "Managed by me" 
4. Click on "Created by Me" filter button, shows all projects that are "Created by me". This removes any of the currently selected "Active", "Draft" or "Archived" filters.

So, if I add a "Managed by Me" filter button, should this button AND the "Created by Me" filter button both be completely independent of the status filter buttons? 

When you select a "Managed by Me" filter button, my assumption is that it shouldn't turn off any of the status buttons ("Active", "Draft", "Archived"). Same for the "Created by Me" filter button - it too shouldn't turn off any of the status buttons.

(_Sorry! Not entirely familiar with the necessary business logic!!_)

**Here's a draft screenshot of the design:**

Hope this looks alright.

![image](https://user-images.githubusercontent.com/12412031/120021726-07f54b00-c01e-11eb-924f-2134230971f1.png)

**Comment by willemarcel** [comment]
Thanks, @NatashaKSS! It looks great! I prefer if we let the user select one status and one option between created / managed by me.
