### ISSUE TITLE
Add new search param to refine mapping type filter

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#3852]
The search param `/api/v2/projects/?mappingTypes=BUILDINGS` right now returns projects whose mapping type field contains buildings, but includes projects set with buildings and other types.

Add a new search param that would filter projects strictly, so in the case mentioned above it would return projects whose mapping type is only BUILDINGS

**Comment by d-rita** [comment]
@willemarcel, To add to this functionality, what should happen when a person selects multiple mapping types? Should the result include projects with all mapping types or any of them? For example, should the search query `/api/v2/projects/?mappingTypes=BUILDINGS, ROADS` return projects strictly with both types, or can the search results include projects with any and both types?

**Comment by willemarcel** [comment]
@d-rita On the backend, I propose to add a new search param, it could be named `mappingTypesExact` to receive a true / false value. The default would be `false` and would make `mappingTypes` work as it is now. If it is `true`, would switch to the exact match. 

Then on the frontend we can add a switch.

@ramyaragupathy what do you think?

**Comment by ramyaragupathy** [comment]
@willemarcel - Yes that sounds right - so it will be,
`https://tasking-manager-tm4-production-api.hotosm.org/api/v2/projects/?mappingTypes=ROADS&mappingTypesExact=true`

It would be nice to have these two as interdependent parameters, so that it `mappingTypesExact` becomes required only if `mappingTypes` is specified. I am checking out options in flask framework for this implementation, @willemarcel - if you're already aware of this, please add.

**Comment by willemarcel** [comment]
@ramyaragupathy I think it's not required to do that check, only assure that `mappingTypesExact` would have any effect if it's alone. If it's not present, the default value is `false`.
