### ISSUE TITLE
User Profile - Not seeing my previous projects on the map

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#387]
I do not see my previous projects on the map.

username: bgirardot

![2017-05-25_06h42_01](https://cloud.githubusercontent.com/assets/265831/26436234/5fb74f6e-4115-11e7-95b7-0b318b1c90a2.png)

**Comment by hunt3ri** [comment]
Hi @bgirardot @pgiraud this problem is stemming from the fact that I assumed that the area.id was in step with the project.id.

I'm very tempted to move the geometry columns that are currently in a seperate AOI table into the project table.  This would simplify a lot of queries, but it would mean that it would enforce a 1 to 1 relationsip, eg 1 project could only ever have 1 AOI.

Thoughts??

**Comment by hunt3ri** [comment]
@davidneudorfer just cc'ing you on this.  Our migration scripts make an incorrect assumption about projects and AOIs which results in this bug.  So we will need to fix and migrate the areas again later.

**Comment by bgirardot-np** [comment]
Hi Iain,

If I understand correctly, you mean only one polygon for an aoi.
I wish we could do that, but projects often have several to many polygons for the aoi.

**Comment by hunt3ri** [comment]
Hi @bgirardot-np 

AOIs are stored as multi-polygons.  So we only need on geometry column, which could live within the project table.

Would mean one less table and not having to join to the AOI table every time we want to get centroid, or bounding box for the AOI.  

Would be a nice refactor, and now would be the time to do it, as it would be a lot scarier once we were up and running

**Comment by bgirardot-np** [comment]
@hunt3ri whatever you think is best as long as we can have the multiple polygons for the "aoi", that is my only concern from a front end perspective.

@pgiraud might have some thoughts on it too from his experience.

**Comment by pgiraud** [comment]
Just a quick note: the main reason why the AOI was in a separate table was to allow several projects to be created using the same AOI. This could be useful if we duplicate a project in order to ask contributors to map roads on the first one and buildings on the second one.
It was probably too ambitious, and I think I can leave with an aoi column within the project table.

**Comment by ethan-nelson** [comment]
From my viewpoint, I don't have a problem with one object (be it multipolygon or single shape) per project. To replicate Pierre's functionality, we could copy the object from a project to another.

**Comment by hunt3ri** [comment]
Thanks @pgiraud @ethan-nelson yeah I think conceptually having the AOI on the project is easier to grok.  Future generations of HOT hackers will thanks us, as they won't have to join to the AOI table every time they want to get the bounding box and centroid 😄 

I'll aim to do the refactor at the start of next week.

**Comment by hunt3ri** [comment]
@bgirardot hi blake I've hopefully resolved this issue too.  let me know.
