### ISSUE TITLE
Add new notification type to handle #managers messages

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#3902]
Some managers don't want to receive notifications when other users add the #managers hashtag on projects/tasks comments. We should add those messages under a new notification type and allow them to disable both emails and notifications.

**Comment by cgiovando** [comment]
I would propose to bump this issue, as I just realized I missed several TM notifications because I had a filter for the many emails that include _#managers_ even if they are not managers of their own projects.

We should add new notification options to choose to receive them when group mentions (e.g. _#author_, _#managers_, etc) are made in comments of _created_, _contributed to_, or all projects.

I may also be good to add options for different notification settings for mentions of their username or the groups they belong to. For example I would like to receive email notifications for all direct mentions (with my username) on any TM project, but only from the projects I created for mentions of _#managers_.

CC @russdeffner

**Comment by hya-barber** [comment]
Suggesting to change the logic of the code that #managers is mentioned, only the notification be send out to respective project manager and not to all managers. Once implemented, get analytics how often or frequency of #managers is mentioned in 1m, 2m,3m and further concerns related to this. If still needed, proceed to add new notification options as suggested above.

**Comment by russdeffner** [comment]
Slight correction - #managers should go to the #author plus anyone assigned the Project Manager role (i.e. on a team assigned as manager to the project)

**Comment by hya-barber** [comment]
Thanks @russdeffner for clarifying. 

The concern I have for embedding right away custom notifications in the settings (1) probably need to conduct TM refresher training across the community for this new feature (2)  Establish clearly defined criteria. for example, what is the default settings, would this add-on customization lead to other future  hash tags customizations as well. If we have analytics to see what are commonly used hashtags and its implication in terms of users desirability and usefulness. Then maybe we can decide which custom notifications we need to add in TM then.

**Comment by russdeffner** [comment]
Thank you @hya-barber for looking into it! 

I do not disagree with this strategy. I would point out that this is actually more of a current bug, in that if someone uses #managers it actually seems to ping all organization admins instead of the author plus anyone on a team assigned to the project. I haven't tested that theory but the origin of the 'complaint' is an HOT admin and is getting messaged from all #managers mentions on all HOT projects. 

If I may, a quick fix could be to just disable the #managers mention and leave the #author so people could still ping someone, although that somewhat defeats the purpose of assigning additional managers via teams.

**Comment by hya-barber** [comment]
Noted on this @russdeffner. @willemarcel  - let's hold the custom notifications. If we can change the notification logic in #managers to inlcude only **authors + manager assigned to the project**, that would be good. Otherwise if takes longer, disable the #managers as suggested by Russ. Also, Let's discuss separately about getting insights of commonly used hashtags in TM.

**Comment by willemarcel** [comment]
I pushed a solution to this issue in #4669:

The #managers hashtag will notify the project author and the members of the teams with Project Management permission on the project. The organization managers will not receive that notification any more.

**Comment by russdeffner** [comment]
Great, thank you Wille! Food for thought - maybe it would be good to have an '#org_admin' mention. Low priority but could see rare want to mention the organization admins if projects are lacking instructions, poorly designed, etc.
