### ISSUE TITLE
Hide option to mark task as unavailable on some situations

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#4082]
After a task is changed from unavailable to ready, we could only show that option again to advanced users on the map page. It will avoid inexperienced users from marking a task as unavailable multiple times.

**Comment by RAytoun** [comment]
@willemarcel  This is building into a serious time wasting for validation. Is it possible to put in an extra page so that when a task is selected for mapping and then "Map selected task" is clicked it first takes you to the next page with the history and the comments open and then they have to click "Map selected task" again to go to the editor? At least this way they will see the comments and then can decide if they want to go further or return to the task selection and choose another task.
