### ISSUE TITLE
Facebook share button - defaults to mobile message and translation strings

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#411]
![2017-05-26_15h50_09](https://cloud.githubusercontent.com/assets/265831/26497321/64c29948-422b-11e7-8282-d6af332a3fcd.png)

**Comment by LindaAlblas** [comment]
@bgirardot I can't replicate your translate issue here. What browser are you using?

**Comment by LindaAlblas** [comment]
@bgirardot I have added some meta tags (description, keywords etc) for SEO purposes so it should not show the mobile warning message but "OSM Tasking Manager is a mapping tool designed and built for the Humanitarian OSM Team collaborative mapping.". You can change this in client/index.html. Try sharing a page that you haven't tried sharing before because Facebook seems to cache requests.

**Comment by bgirardot** [comment]
This seems fixed. Any chance of getting some project specific text in the FB post? First paragraph or x number of words/characters from the full description maybe?

the URL is project specific, that is good.

**Comment by LindaAlblas** [comment]
Twitter allows you to add text and hastags, e.g. 'I have just contributed to this project http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/project/2648 #hotosm'

Facebook only allows you to share a URL if you don't have a Facebook APP ID. To get a APP ID, you need to have a Facebook developer account (https://developers.facebook.com/docs/apps/register). If HOT has a Facebook APP ID then we can add a description.

**Comment by bgirardot** [comment]
Hi Linda,
I will see if we can do that, I am pretty sure we do not have anything like that.
thanks for the background linda.
I am going to close this then as the issue is fixed to the best of our ability for the moment.
