### ISSUE TITLE
LinkedIn hyperlink on userpage malformed

### ISSUE THREAD

**Issue by vdgwebsites** [hotosm/tasking-manager#4157]
The LinkedIn hyperlink on the TM userpage is malformed and results in a Page not found.

`https://www.linkedin.com/in/https://www.linkedin.com/in/martienvandegriendt/`

**Comment by LittleStar21** [comment]
I'd like to work on this.

**Comment by LittleStar21** [comment]
Hello, so this is what I figured out when working on this task.
![Screenshot (12)](https://user-images.githubusercontent.com/48920862/109469747-68b9c980-7aa9-11eb-9a69-c907fe745b2f.png)
When I prompt my LinkedIn's url, there's warning that said to type my username and it did not let me press the save button. 
![Screenshot (13)](https://user-images.githubusercontent.com/48920862/109470004-c817d980-7aa9-11eb-99c0-9e0b2f5431b5.png)
However, when I prompt my LinkedIn's username, then I can press the save button. Therefore, I think this issue is solved, or am I missing something?
