### ISSUE TITLE
Single task validation should not send a polygon to JOSM

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#437]
When I select a single task to validate, a polygon gets sent to JOSM, but that should not happen as it will get uploaded to osm.

This behavior is fine with multi task selection as the layer the polygons are on is marked to not upload, but with the individual tasks for validation, the polygons are on the same data layer as the automatically downloaded osm data.

**Comment by feenster** [comment]
Hi Blake, looking at this with a view to fix today.  Had an initial look.  My initial plan would be to try and get the task polygon and the osm data on to separate layers in JOSM, so that a single square can still be shown.  If I can't achieve that, I will change the logic so that no square is sent for single squares.

**Comment by feenster** [comment]
@bgirardot I have push a couple of fixes:

PR #477 to use upload = false instead of upload = no
PR #479 to change order of josm remote commands and to load the task square(s) and OSM data into separate layers.

I am stopping work now, and on leave until Monday.  Please watch for those PR's getting merged and then have a play and let me know if these fix this issue.

**Comment by feenster** [comment]
#471
