### ISSUE TITLE
Improved metrics for mapper selection in validation

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#453]
Improved metrics for mapper selection in validation
(2 additional columns on the existing mapper list UI, days since last validation, days since signed up for tasking manager)

**Comment by LindaAlblas** [comment]
@bgirardot we have added the days since last validation and the days since signed up to the existing table as requested.  There is a lot of information now in this table and might look a bit intimidating to a new validator which is what we were trying to avoid. Also, the table doesn't get displayed nicely because it has become so big. 

We'd suggest reviewing this and potentially removing a few columns to keep it simpler for the average validator. Sorting the table could be done by the server and return the list of users in a sensible order. Validators would then be directed to validating users without thinking too much about it. They could just start validating users at the top of the list first.

Any thoughts?

**Comment by bgirardot** [comment]
I am looking linda.

**Comment by bgirardot** [comment]
We could, maybe:

Changed "mapped" to "Qty" for quantity or just # for number.
change "start validating" to "validate" or "start", "open"
If possible just show the time past in hours and days, no need for "weeks, months, years, and ago"
60d, 12h, 3,650d (for some reason I like this more than days, months, years, etc)
would could lose "Newest" from the UI (like to keep the support for it, just not display it)
make the map a bit smaller

**Comment by hunt3ri** [comment]
@bgirardot would it not be infinitely simpler to just order the mapping contributions on the server and instruct validators to validate from top to bottom?

All this data seems extraneous, and could be hidden from view to simplify the UI while still getting the result you want of validators validating new contributions from mappers who havent mapped for some time first?  

Resulting is a far less intimidating UX for new validators.

**Comment by LindaAlblas** [comment]
I have implemented a few of @bgirardot suggestions in the meantime:

- 'mapped' to '#'
- 'start validating' to 'start'
- removed 'newest' from the UI (it is still returned by the API)
- made the map smaller

Displaying the time is done by a library so I haven't changed that

**Comment by bgirardot** [comment]
@hunt3ri The whole point is that different validators care about different criteria for deciding what to validate. We are trying to give them as much info and options as we can so they can decide where to spend their validation time. I am a little less concerned about UI for validators, they should be able to handle a little complexity, but it does not seem too complicated to me.
