### ISSUE TITLE
Markdown not rendered short description grid or list view

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#462]
In the below example the markdown for links is not rendered.

![2017-05-30_20h51_35](https://cloud.githubusercontent.com/assets/265831/26599768/0c7bf69c-457a-11e7-88ea-8fb210260a7b.png)

![2017-05-30_20h51_25](https://cloud.githubusercontent.com/assets/265831/26599774/12c3a1da-457a-11e7-97ed-c6d1a121ff6a.png)

**Comment by LindaAlblas** [comment]
This is because the short description is limited to 100 characters and the URL happens to be exactly at that cut-off point so it can't render it. The only way to prevent this from happening would be to remove the character limit. See the images below. Let me know what you think.

<img width="504" alt="contribute-no-character-limit-list" src="https://cloud.githubusercontent.com/assets/3329074/26627395/3f17d314-45f2-11e7-89d9-705ff8d7bd59.PNG">
<img width="498" alt="contribute-no-character-limit" src="https://cloud.githubusercontent.com/assets/3329074/26627394/3f179f66-45f2-11e7-9967-2dca74f1c848.PNG">

**Comment by LindaAlblas** [comment]
@bgirardot, removing the character limit does mean that the height of the project boxes could differ a lot more. See image below.

<img width="444" alt="contribute-no-character-limit-height" src="https://cloud.githubusercontent.com/assets/3329074/26627600/f3b38110-45f2-11e7-88b0-d8c79b71cc5a.PNG">

**Comment by bgirardot** [comment]
can we move the meta data stuff above the short description and add in the type of mapping to the meta data listing?

**Comment by LindaAlblas** [comment]
I have removed the character limit and moved the metadata above the short description. The type of mapping is not currently returned from the API so that was not added.
