### ISSUE TITLE
Contribute page defaults to "beginner" filter - should be all

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#464]
If we are just looking at the full project listing, with the "advanced search options" hidden, there is a default "beginner" filter.

when you click on show advanced search, you can see it comes in with beginner instead of all for the difficulty.

**Comment by bgirardot** [comment]
I see what is happening. We are defaulting to experience level of the user.

Have to think about this as when that is hidden it can be confusing.

**Comment by bgirardot** [comment]
An alternative might to show all, but put a little green check icon with tool tip that says "this project is best for your experience level"

**Comment by tastrax** [comment]
I think the sort order is Priority, Level and then maybe Project ID (although that doesn't appear the case when filtered by Intermediate). Bit hard to tell when I can only see a few tasks on any one screen.

Not sure how this changes when a user 'progresses from beginner to intermediate"

#427 also talks about some sort on 'most recent' (update?) rather than Project ID - maybe that's the third OrderBy

**Comment by bgirardot** [comment]
Having worked with this for a few days now, I for sure think that the project listing should default to all, all, all and only filter when someone actually applies a filter.

@tastrax I am going to catch up with your other feedback items as well.

**Comment by tastrax** [comment]
I tend to agree Blake - I have noticed mine (when logged in) is now filtered by advanced by default (which throws up no projects). I think from a HOT perspective its best to show all by priority as the default, and then let folks filter to what they want.

**Comment by hunt3ri** [comment]
@LindaAlblas has resolved this.
