### ISSUE TITLE
Refine and Enhance "Seeing existing projects' AOI"

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#4957]
More work is needed from #4723 

Currently you need to zoom much too far in before you can click the 'Show existing projects' checkbox. In the example below, I had to zoom almost all the way into the city of Beira, Mozambique (when the scale bar is 3km).
![BieraEx1](https://user-images.githubusercontent.com/6763645/148874219-96f1b4d7-2e5b-4d0d-b230-d75201bcd1b2.PNG)

However, to get a good sense of the project AOIs in the area, I need to be zoomed to around 10km on the scale bar...
![BieraEx2](https://user-images.githubusercontent.com/6763645/148874477-db53cd54-c059-4f96-bc86-515cfd350b03.PNG)

Simply, the ability to show existing projects should be allowed at 3 or 4 zoom levels out from where it is now.

What would be even more interesting and possibly helpful is if at beyond that more appropriate zoom level, the centroid of project AOIs would show. Because even more importantly: **these AOIs dont really help me** determine what those projects are, how I could find at least a project number and/or the features that were mapped and other metadata that would help avoid duplication of efforts, imagery offset issues, etc. etc.

Here is an example from Kontur (disaster.ninja) which shows the centroids (clickable and take you to the project). Also shown is their "Quantity Layer" which can give an idea of how 'well mapped' an area is.

![CentroidEx](https://user-images.githubusercontent.com/6763645/148876608-47394fdc-ff1c-46f4-b3ef-160d9af62fd5.PNG)

Lastly, to help new project creators; maybe these project centroids and/or AOIs should be **turned on by default**.

Thank you for considering this change that could greatly help avoid data quality and duplication of effort issues!

**Comment by SColchester** [comment]
+1 Forgot that this had been added and was about to create a new issue. Here's hoping there is a fix 😄 🤞

**Comment by HelNershingThapa** [comment]
Hi, @russdeffner @SColchester, I'm trying to take up this issue and was seeking a high-level overview on its implementation. I've attached a video that has the following changes:
- A layer with the existing project number is added and is visible at all zoom levels.
- Project AOI is viewable from zoom 9; it's currently implemented at zoom 11 on the live server.
- Existing project AOI checkbox is turned on by default.
- A loading indicator beside the 'Show existing project' checkbox label shows that the AOI is being fetched.

https://user-images.githubusercontent.com/51614993/180741897-4e4bfea0-ce11-499f-852f-22d0bdb67bbe.mp4

There's a 1.5 seconds delay in fetching the projects AOI on map events (zooming, panning), so there's a slight delay in bringing the AOI. This was done so that the API would be fetched after some idle time in map events; otherwise, we'd be making requests on change in every map event, which would require a lot of computation. 

I understand it's reasonably uneasy to understand the changes from the above video; I'll send out a PR if the above implementation is fine by you, and further testing could be done on the staging server.

**Comment by SColchester** [comment]
This looks great!

**Comment by russdeffner** [comment]
Yes, great to see some progress here.

**Comment by HelNershingThapa** [comment]
Hi @russdeffner @SColchester, please find the changes on the staging server and let me know how you like it.
