### ISSUE TITLE
TM not available after starting with docker-compose

### ISSUE THREAD

**Issue by ltog** [hotosm/tasking-manager#5008]
I was trying to have first look at TM using docker / docker-compose. Specifically I used the manual at https://github.com/hotosm/tasking-manager/blob/develop/docs/setup-docker.md .

Basically I ran `docker-compose up -d`. I got the output

```
Starting postgresql                 ... done
Starting tasking-manager_frontend_1 ... done
Starting tasking-manager_traefik_1  ... done
Starting migration                  ... done
Starting backend                    ... done
```

but no service runs at http://127.0.0.1:5000 .

How can I debug this? The manual probably should also be amended with this information...

**Comment by Aadesh-Baral** [comment]
@ltog  I think TM frontend is available at `localhost` and API is available at `localhost/api/`. You can try `localhost/api/v2/system/heartbeat/` to check if API is running. You may also need to set `TM_APP_API_URL=localhost` on  `tasking-manager.env` before building the frontend image file so that frontend can access API.

**Comment by ramyaragupathy** [comment]
stale and we have had several setups running through docker after this.
