### ISSUE TITLE
Error while switching between RapiD and iD editor after RapiD integration.

### ISSUE THREAD

**Issue by Aadesh-Baral** [hotosm/tasking-manager#5025]
There is an issue while switching between RapiD and iD after the integration of RapiD on the staging instance. There is no issue if there are no user changes. Also, there is no issue if the user clicks on reload button presented on the popup. But there is an issue if the user clicks on the cancel button on the popup.
To replicate this issue:

- Select any tasks to map in RapiD enabled project on [staging](https://tasks-stage.hotosm.org). [[Project with RapiD enabled ](https://tasks-stage.hotosm.org/projects/8616)]
- Make changes using RapiD or iD without uploading changes.
- Try reloading the editor. Switch to RapiD if you made changes using iD and vice versa.
- Click `cancel` on the popup.

Known Issue if clicked on cancel while reloading from iD to Rapid:
- Returns error page with `An error occurred ` that does resolve using `return` button until the page is reloaded.
![Screenshot from 2022-03-02 16-56-22](https://user-images.githubusercontent.com/67958673/156497983-557f6210-bfb8-41f5-a201-fc7e24f55c06.png)

Known Issues if clicked on cancel while reloading from RapiD to iD:
- All of the changes are lost.
- Icon of RapiD assist doesn't appear.
- RapiD assist layer color is changed.

![Screenshot from 2022-03-03 10-33-36](https://user-images.githubusercontent.com/67958673/156499695-f3a6e529-e706-4a84-896d-bd9e36bb8b22.png)

**Comment by Aadesh-Baral** [comment]
I don't think there is any use case for switching, but the user may still do it and get stuck on the error page or lose all of their changes. I think if the user clicks on `cancel` on the confirmation popup after switching it should return to the state that was before.

**Comment by zlavergne** [comment]
Thanks for the details @Aadesh-Baral . I agree that this isn't a real use case that needs to be supported at this point. I'll look into the issue of losing edits when clicking on the `cancel` button.

**Comment by zlavergne** [comment]
@Aadesh-Baral I've dug into the issue and I think I've found the culprit. When selecting an option from the **Reload Editor** dropdown, it calls [callEditor](https://github.com/hotosm/tasking-manager/blob/8cffe3420563cdb59170442e7ede14d08ebe993b/frontend/src/components/taskSelection/action.js#L132) which is what ends up navigating to the new URL. So essentially, the order of events is:
Click editor in dropdown -> navigate to url with that editor -> editor (iD or RapiD) presents confirmation prompt

Regardless of what the user selects in the prompt, the page is already navigating to the URL for the new editor and isn't respecting the prompt of the child component at all.

When the user selects **Reload** everything works because the underlying components are able to cleanup properly. 

I'll have a PR out when I figure out a clean solution but I wanted to share the findings.
