### ISSUE TITLE
[BUG] Search doesn't handle bad queries very well

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#5118]
**Describe the bug**
When searching a project, it fails if the search query has some bad characters. We should handle this more cleanly. So far it doesn't like `|\/`, but probably more. See https://sentry.io/share/issue/f54a1508bfb64a43a14ed3ae3dd758a2/

**To Reproduce**
1. Go to https://tasks.hotosm.org/explore
2. Type in the project search `12373 | | | HOT`
4. See error in results. 

**Expected behavior**
The project search should ignore irrelevant characters , or fail gracefully. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1847818/167182149-2950d07a-900a-46aa-a9ca-6eed7c6639a9.png)

**Additional context**
This was discovered in relation to the 5 May 10:00am incident where TM was inaccessible for around 40 minutes. We are still determining the cause but this may be related to a 700 person mapathon occurring during that time.

**Comment by dakotabenjamin** [comment]
I think it's this function: https://github.com/hotosm/tasking-manager/blob/532aa94ad205e7db21165f68ef50775d14084cd0/backend/services/project_search_service.py#L66

**Comment by dakotabenjamin** [comment]
I'm more convinced that this issue was in fact the cause of this morning's disruption. The breadcrumbs in the sentry issue above contain the following subquery: 
```
SELECT users.id AS users_id, users.username AS users_username, users.role AS users_role, users.mapping_level AS users_mapping_level, users.tasks_mapped AS users_tasks_mapped, users.tasks_validated AS users_tasks_validated, users.tasks_invalidated AS users_tasks_invalidated, users.projects_mapped AS users_projects_mapped, users.email_address AS users_email_address, users.is_email_verified AS users_is_email_verified, users.is_expert AS users_is_expert, users.twitter_id AS users_twitter_id, users.facebook_i...
```
Unfortunately the breadcrumb is truncated but it does line up with the query that was running up the most number of Active Average Sessions (an abstraction of cpu usage in Amazon RDS), hogging the db connections, and causing the backend latency etc.
![image](https://user-images.githubusercontent.com/1847818/167212223-ef80beb8-d56c-4bb3-b146-a5867cbd4895.png)

![image](https://user-images.githubusercontent.com/1847818/167212292-e873e7ec-8403-4081-8ce0-545484240f6e.png)

This is also corroborated in the logs, which i won't post here for privacy reasons.

**Comment by Aadesh-Baral** [comment]
Hi, @dakotabenjamin I went through the code that handles text search and found out that some of the special characters represent text search operators like` | ` representing `or` operator ([more info](https://www.postgresql.org/docs/current/functions-textsearch.html)). That's why it returns an error when these special characters are used in text search. I do agree this has to be handled but I don't think this was the reason for TM being inaccessible for around 40 minutes. 

I went through the logs and found out that most of the failed requests were caused due to exceeding database  [pool_size](https://docs-sqlalchemy.readthedocs.io/ko/latest/core/pooling.html#sqlalchemy.pool.QueuePool.params.pool_size) and [max_overflow](https://docs-sqlalchemy.readthedocs.io/ko/latest/core/pooling.html#sqlalchemy.pool.QueuePool.params.max_overflow) both of which are set to 10 in our case. I think TM being inaccessible is related to high user interaction due to 700 person marathon. This also aligns with the subquery that you shared above as this query is used to create/update users on the TM database during user login. 
Apart from that most of the other failed requests are due to the bad response from OSM during OAuth and fetching user details from OSM both of which also happens during user login. I think all of these logs are pointing towards a very high no. of users trying to access TM.

**Comment by dakotabenjamin** [comment]
Agree that there are separate issues here, one for the operators handling and another for the downtime. But given the sheer number of queries stemming from the project search happening at that time, it's definitely related. 

I'll take a look at the infrastructure-related database configuration and see if we should increase those values.
