### ISSUE TITLE
Allow validators to see and filter archived projects

### ISSUE THREAD

**Issue by aawiseman** [hotosm/tasking-manager#5128]
**Is your feature request related to a problem? Please describe.**
Validators need to be able to validate archived projects, but right now the only way to see them is type the number, and that's only possible if they know which project to look for. If possible it would be good to allow validators to filter or see archived projects.

This was suggested as one of the ideas from the HOT Data Quality Working Group

**Describe the solution you'd like**
Allow validators to filter or see archived projects. Maybe it's tied to their access level in the TM

**Comment by SColchester** [comment]
Definitely agree, would extend this and argue that it would be great for the **general public** to see a searchable, filter-able list of archived projects. At the moment public need to know that the only way to see an archived project is to add the project number to a URL - this is fairly specialized knowledge and I worry that people struggle to discover the history of old projects.

**Comment by Ichchhie** [comment]
I think we can add new option for "Archived projects" in the popup as shown in the screenshot.
![Screenshot_333](https://user-images.githubusercontent.com/33247422/180745666-8ea82c46-a5c2-47b0-8fd4-f044c9cdc426.png)

**Comment by zlavergne** [comment]
I again agree with @Ichchhie here! Adding an item to the dropdown would be the simplest solution here.

One question though (likely for @aawiseman and @SColchester) what happens after we surface these? The concept of "Archiving" something exists as a sort of "read-only" state (which is why I agree being able to search and filter for them is necessary). But say someone explores projects and starts looking at the archived ones, should we allow them to map/validate the project while it's still archived?

This would add complexity to the implementation but I'm thinking it might make sense to restrict "actions" on archived projects. Maybe we can change the "Contribute" button for an archived project to "request to un-archive" (or hopefully a more elegant message) which could send a message/notification to the PM team that user x wants to work on this project. This is likely an edge case but one I thought might be worth discussion anyway.

**Comment by SColchester** [comment]
@zlavergne great question - yes, Archiving should definitely shift the project to a 'read only' state. I thought this was the case already but your question has helped me identify that you can actually contribute to Archived projects ([like this one](https://tasks.hotosm.org/projects/10485)) - this is likely a mistake, and has not been too much of an issue yet because it is hard to find archived projects. If archived projects become easier to find this will cause more of an issue. 

I really like the suggestion about "Request to un-archive", this could reduce the amount of project duplication when areas need to be revisited for mapping. The easier option is to change the 'Map a task' option to the typical option for projects which are 100% mapped and validated: ' Select another project'.

![2022-07-28 11_24_14-](https://user-images.githubusercontent.com/43822967/181610773-c1da9370-0626-4de9-baba-44a4c706c287.png)
