### ISSUE TITLE
Adding RapiD as an editor option under Editing tools

### ISSUE THREAD

**Issue by asturksever** [hotosm/tasking-manager#5139]
[RapiD ](https://wiki.openstreetmap.org/wiki/RapiD) is a modified version of the iD editor allows editing roads and building by suggested edits. Having RapiD as an option under Editors list, will help to speed up adding more features to OpenStreetMap. 

I'd like to request RapiD editing option to be able to contribute tasks by RapiD editor. Please see attached screenshot.

<img width="1277" alt="Screenshot 2022-05-20 at 15 57 09" src="https://user-images.githubusercontent.com/28983926/169559589-127b04ff-6d9f-4360-b747-1d32cff984fe.png">

**Comment by HelNershingThapa** [comment]
RapiD is already a part of the TM ecosystem. You cannot see RapiD as one of the editors in your project since it has not been enabled in the project's settings. To use RapiD, it must be enabled when creating/updating a project

![selection](https://user-images.githubusercontent.com/51614993/169748330-7337368a-9444-4adc-91f1-ac0f10029c9b.png)
.
