### ISSUE TITLE
Project Creation: Existing Project AoIs - Can we show at more zoomed out level?

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#530]
The toggle switch I think works well. but given the very large areas some of the project cover, can we enable that a more zoomed out view?

**Comment by feenster** [comment]
fixed with #549

**Comment by bgirardot** [comment]
@feenster Can we bump this out 2 more levels?

do we have any info on performance issues? It seems to take a few seconds to fill in, but really, this is not going to be used very often, only during project creation which probably happens just 5 or 10 times a day.

**Comment by feenster** [comment]
@bgirardot I have increased by 2 zoom levels.

The concern is around the size of the responses and performance over slow connections.  Because we are returning the raw, ungeneralised project geometry in the response, the response payload could get pretty big.  Therefore the response will take longer on slow connections.  Just to give an idea, the response data size for the attached map was 2.9MB.  The response times for that map on different connections speeds were as follows:

750 kbps (regular 3G) - 30 seconds
2 mbps (DSL) - 15 seconds
30 mbps (wifi) - 4 seconds

![image](https://user-images.githubusercontent.com/16537909/27181026-a549ef3c-51cd-11e7-9d6a-f3fe6d7e5ae1.png)

**Comment by bgirardot** [comment]
Ok, lets see what happens. Lets just reference pull request #575 allow 2 zoom levels further out and we can adjust as needed.

Thanks very much!

**Comment by mikelmaron** [comment]
Solution here could be to generate vector tiles periodically, rather than send raw GeoJSON to the browser
