### ISSUE TITLE
[BUG] Can't log in

### ISSUE THREAD

**Issue by ChildishGiant** [hotosm/tasking-manager#5372]
**Describe the bug**
When trying to log in a new about:blank

**To Reproduce**
1. Go to https://tasks.hotosm.org/
2. Click on login
3. Note the new blank window open

**Expected behavior**
To be sent to a page to login (in a new or existing window).

**Desktop:**
 - OS: Linux Mint
 - Browser: Replicated on chrome v106.0.5249.91 and firefox v105

**Comment by Aadesh-Baral** [comment]
This was due to OSM server issues rather than Tasking Manager. There may be a need to display an error message indicating that a connection to OSM could not be established;  this requirement should be investigated following the implementation of OAuth2. Everything is working normally, so closing this issue.
