### ISSUE TITLE
Accessing (via url) a non-existing project id seems to 'create' it

### ISSUE THREAD

**Issue by PaulUithol** [hotosm/tasking-manager#543]
Steps:
- put a clearly non-existing project number in the url, e.g. http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/project/10000005

Actual result:
- You'll get a blank, new project ("Last updated: 2 minutes ago")

Expected result:
- Error message; project does not exist, with a link back to the main contribute page

**Comment by ethan-nelson** [comment]
Looks like this has mostly been fixed in the related pull request listed above. Though, if you keep the browser open, every ten seconds it will poll the server again and temporarily show a blank template. It may or may not be worth it to turn off autorefresh if a project cannot be found (~0.16 KB is transferred per 10 seconds).
