### ISSUE TITLE
Per project comments - super neat, kind of slow to post

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#544]
Just a note as something to investigate: When I put a comment on the project, it takes about 30 seconds for it to appear. Not sure why that is, but could lead to a bit of confusion on the person leaving the message, "did this get lost? did it get my comment?" etc.

I expect it to be pretty low volume of comments so maybe if it is because there is just a normal "update cycle" that has to happen, we could trigger it on submitting a comment so people know it got posted.

or some sort of "posting ....." so they know something is happening.

**Comment by bgirardot** [comment]
user feedback confirms this happens and causes confusion.

**Comment by hunt3ri** [comment]
It's important to underline that this chat feature does NOT support Real Time chat.  We are using HTTP not sockets so we couldn't support dozens of users chatting using this feature, which is why you can see some delay.

We've already pushed some optimizations about how often chat is refreshed, but if two users are trying to maintain a realtime conversation then we could provide a link to slack or similar?

**Comment by bgirardot** [comment]
ya, this is not real time chat.

We are going to change the title from "Chat" to "Questions and Comments" so it is less likely to be viewed as real time chat.

But the really log delay is still confusing, even when not thinking of it as real time chat. I'll test and see if the changes have improved it.

**Comment by bgirardot** [comment]
Oh, looks like I already changed it to discussion. Still probably "questions and comments" is more clear.

**Comment by bgirardot** [comment]
This issue looks fixed to me, it immediately indicates the comment has been posted. Hopefully that fix was posted some time in the last 7 days as the feedback was from 7 days ago :)
