### ISSUE TITLE
[BUG] Project card missing priority label

### ISSUE THREAD

**Issue by Aadesh-Baral** [hotosm/tasking-manager#5455]
Project card is missing priority label for medium and low priority projects.
![missing_priority](https://user-images.githubusercontent.com/67958673/206358565-b71efaa5-0dc6-45f7-be0c-87f1d9a70204.png)

**Comment by HelNershingThapa** [comment]
Before we merge this pull request, I suggest we take into account why priority boxes were hidden for medium and low projects in the first place.

cc @ramyaragupathy

**Comment by ramyaragupathy** [comment]
@HelNershingThapa - I remember a design convo about this where we wanted to flash only `high` and `urgent` priority projects. If we include all priority labels, then we should think about translating the priority message via right color choice.

**Comment by HelNershingThapa** [comment]
The color options had already been assigned @ramyaragupathy. The pull request simply removes the conditional to show the priority labels so that it appears on all cards.
![priority-boxes](https://user-images.githubusercontent.com/51614993/207020926-f0aeea9b-b05e-42dc-96db-a987b197473a.png)

However, the color scheme used in the implementation differs from the [design's](https://www.figma.com/file/WcfqNTm0UKM4iFTConGbnI/HOT_Web_High-Fidelity-(Branded)-(1)?node-id=0%3A2185&t=wJgoyxOvsGrU3TJU-0).
