### ISSUE TITLE
Bad Imagery state doesn't allow validation

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#551]
Currently if someone marks a tile as bad imagery, if you try to validate the tile it says it's in a state that cannot be validated. Discussing with a few people, this seems wrong as we do need a way to 'double-check' and say 'yep, this tile cannot be completed, but we want to show we did all we could to get a project to 100% done and validated.'  It still would be good to record a tile as bad imagery but also 'validated' to show project completion.

**Comment by feenster** [comment]
That is correct, you cannot currently lock a tile for validation, so it is not currently possible to move a tile from badimagery directly to validated.

It is however possible to lock it for mapping, so it would be possible to do: lock-for-mapping -> mapped -> locked-for-validation -> validated

**Comment by feenster** [comment]
The part about validating a badimagery task has been Fixed by #581.

TM3 does not currently support holding a task as being validated and bad imagery at the same time.  A task can only have one status at a time.

The task history could be used to derive that a validated task was in badimagery status immediately before it was validated.
