### ISSUE TITLE
Incorrect markdown url in wysiwyg editor

### ISSUE THREAD

**Issue by martien-176** [hotosm/tasking-manager#5546]
**Describe the bug**
When entering a random url into the editor and then mark it up with the toolbar link button the result is a hyperlink linking to https://tasks.hotosm.org/projects/url. 

**To Reproduce**
1. Go to TM editor (project chat or task)
2. Enter url in editor
3. Click url markup button in editor toolbar 
4. Resulting url links to https://tasks.hotosm.org/projects/url

**Expected behavior**
Resulting url links to correct url

**Screenshots**
![Animation3](https://user-images.githubusercontent.com/17877665/215333838-0790b389-5a93-46e1-922a-6f6fc3b5830a.gif)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser ms edge / firefox
 - Version 109.0.1518.70 / 109.0 (64-bit)

**Additional context**
Example: https://tasks.hotosm.org/projects/14005/tasks?page=1&search=1

**Comment by martien-176** [comment]
Here another example of a url going wrong:

![hyperlink-issue](https://user-images.githubusercontent.com/17877665/218069395-2422476e-cae6-4152-91e6-b495dd9b83d6.jpg)

**Comment by HelNershingThapa** [comment]
@martien-176 Sorry to break it to you; neither of them is a bug. The code is syntactically correct; however, given how markdown functions, you should have presented the URL differently. I also addressed this on the Slack [thread](https://hotosm.slack.com/archives/C319P09PB/p1675003632767929), but I didn't remember to close it at the time.

We are a little perplexed here because we assume that when we click the link button on the toolbar, the text would be regarded as a link, but because Markdown has been implemented in the comment textarea, we must adhere to the Markdown syntax as described [here](https://www.markdownguide.org/basic-syntax/#links).

The current implementation expects the selected text to be the label text and the users to replace the 'url' text with the corresponding URL for the label. We can improve here by programmatically determining whether the selected text is a label or a URL before putting it in the appropriate brackets when the user clicks the link button to improve the user experience here.

Thank you for bringing this up; the Tasking Manager ecosystem is new to the Markdown comment section with the toolbar and might benefit significantly from user experience enhancements like these.
