### ISSUE TITLE
Task comment screen vanishes while writing a comment

### ISSUE THREAD

**Issue by martien-176** [hotosm/tasking-manager#5574]
**Describe the bug**
After writing a comment the task screen from eg task #X switches to the task screen from task #Y. The end result it that the comment that was meant for task #X is placed in task #Y.

**To Reproduce**
1. Go to the task comment section and write a task comment
2. Click on the 'Comment' button
3. Check the task comment you just wrote and saved
4. You see that it is saved to another task

**Expected behavior**
The task comment should be saved in the task you were doing

**Screenshots**

![task-comment-disappear](https://user-images.githubusercontent.com/17877665/217828193-2069053e-b69f-4948-b0d9-b67d7a0408cf.gif)

This is what happens in the gif:
~~1. open task 810 to copy comment made earlier
2. paste it in, but it ends up in task 675, a the task that was not aimed for~~

1. open task 810 to copy a comment made earlier (for use elsewhere)
2. within a few seconds the comment box for 810 disappears and is replaced with the comment box for task 675

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser MS Edge
 - Version 109.0.1518.78

**Additional context**
This issue is reported by several users and discussed in Slack:
https://hotosm.slack.com/archives/C319P09PB/p1675891636223039

**Comment by shiller27** [comment]
This happens to me when accessing the comment history for a validated task from the task history to
1. copy a comment from a task previously validated by me for use elsewhere (as in the gif above)
2. write a comment under a task validated by another person, for example after having reverted it from validated to mapped) - the comment may then get posted on the switched comment section rather than the intended one, or disappear altogether

Sometimes it can take up to a minute for the comment to switch, sometimes it happens within seconds, for that reason it is almost impossible to replicate/screencast 2.

**Comment by HelNershingThapa** [comment]
@martien-176 @shiller27 I attempted to duplicate the problem, but I could not. What you have faced is unexpected and annoying. I was baffled by how the task dialog abruptly changed from 810 to 675. I can see the mouse pointer in the attached image's right bottom, but more clarifications on what actions were done there would be more helpful. The comment section, however, functioned well when I followed your instructions to duplicate the problem. 

I've been following the Slack conversation as well, and while I realize that the discomfort was felt by other people and had been challenging to reproduce, we could use a few more hints to do so.

**Comment by Kraan46** [comment]
You can reproduce it when you choose a project where many mappers are working at the same time and one task after another is declared ready. It is this that shifts the list of tasks.

**Comment by shiller27** [comment]
@HelNershingThapa you can see the mouse pointer moving because after the comment box switched to 675, I ticked the stop button on the gif app (which is at the right bottom). I just replicated it while writing this post (with the gif app running) - this time it took over 2 minutes, maybe because fewer people are working on the project? I can post this second gif if it helps?

**Comment by shiller27** [comment]
I didn't crop it, so a little boring to watch... 
![GIF 2 comment box issue](https://user-images.githubusercontent.com/19452020/217900312-46b912b8-ad9c-40af-8b4d-b36faddec23c.gif)

**Comment by shiller27** [comment]
Early on in the clip I moved some stuff to the other monitor, hence the unexpected action! But definitely didn't do anything that triggered the comment box disappearing

**Comment by ramyaragupathy** [comment]
@martien-176 @shiller27 @Kraan46 - are you still facing this issue?

**Comment by Kraan46** [comment]
Here you can see what i mean: while i was reading the comment in task 933, task 1180 is validated and the list shifts so that the comment in task 933 vanishes and the comment in task 1180 becomes visible. So if i would have wanted to copy or comment in task 933 i suddenly (because there is a new task on top of the list ) and i get to view the comment in the other task 1180:
![2023-03-21 10_11_56-#14311_ Missing Maps - Earthquake Syria, Idlib District (Rural) - HOT Tasking Ma](https://user-images.githubusercontent.com/73127829/226563578-7ed72e11-9f37-4d69-a6bc-3f3bf59d3211.png)
![2023-03-21 10_15_53-#14311_ Missing Maps - Earthquake Syria, Idlib District (Rural) - HOT Tasking Ma](https://user-images.githubusercontent.com/73127829/226563611-ea5110dd-4ee1-4a3c-ba52-778c65fee59d.png)

**Comment by shiller27** [comment]
Hi @ramyaragupathy , yes it is still happening to me, too. I now avoid writing into comment boxes that are opened from the history list, but even reading them can be hazardous...! Let me know if you need more screenshots/GIFs

**Comment by Ichchhie** [comment]
My observation so far:

The problem stated [here](https://github.com/hotosm/tasking-manager/issues/5574#issuecomment-1477559252) occurs when a user selects the first item on the tasks list, but the list is refreshed before the user can perform an action on it, causing the first item to move down the list. For example, if Person X clicks on the first task in the list to leave a comment, but Person Y performs an action such as marking a task as "Ready for validation" at the same time, the comment section will refresh and display the latest item in the first position of the list. This cause the previously selected task id to be replaced with the newer one.

Screenshot of the scenario of the change in task lists that causes the issue:
![Screenshot 2023-05-01 110435](https://user-images.githubusercontent.com/33247422/235429453-ef9bd799-ac86-4482-bfd5-96938b87159c.png)
![Screenshot 2023-05-01 110513](https://user-images.githubusercontent.com/33247422/235429505-ebee7c16-b083-48ca-ba62-f0506ea8b67c.png)
![Screenshot 2023-05-01 110723](https://user-images.githubusercontent.com/33247422/235429457-7e2c1025-1765-4da5-9073-592568a04084.png)

**Comment by HelNershingThapa** [comment]
Wow @Ichchhie, it all makes sense now--thank you so much for your fantastic observation of the issue! I've personally been struggling with reproducing this issue for months, and your insights have been a game-changer in the ability to reproduce it. I'm eager to implement the solution to ensure that this issue doesn't occur again. Your explanation of why this issue is occurring has shed light on the problem and given us some understanding of how to address it—truly appreciated @Ichchhie didi, tysm.
