### ISSUE TITLE
TM2 to TM3 Transition - Can we run in parallel and not lose any info idea

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#560]
@hunt3ri 

I would like run the tm2 and the t3m in parallel and not lose information as we transition over to TM3.

My idea is: When we make the TM3 live, can we start the project numbers for new projects at some arbitrary number like 7000 so we could continue to merge in database dumps from TM2 without it affecting new projects?

Right now the TM2 project numbers are up to about 3200. 

I am hoping we can just keep updating the TM3 DB with TM2 data.

This would obviously only work until TM2 hit 7000 but hopefully by then, hopefully well before then, we would be fully transitioned to TM3.

**Comment by pgiraud** [comment]
Are you scared of the transition?

In my opinion, this will be a nightmare to maintain the data between the two.
2 options in my opinion:
 - start TM3 with an empty database, and let TM2 live and eventually die
 - let TM2 die as soon as TM3 is setup.

**Comment by hunt3ri** [comment]
I agree with @pgiraud keeping two databases synched will be nightmare

I think the strategy should be:

1.  Create a bunch of test projects in TM3, around 5-10
2.  Create a redirect from TM2 to TM3, so that ALL HOT traffic is redirected to new TM3 for at least 1 hour at when-ever is your typical peak load.  Notify the community before hand that this is happening.
3.  Monitor TM3 very closely to ensure it can handle the load, leave the redirect in place as long as the servers are coping.
4.  If we see perf problems immediately remove the redirect on TM2, team can do root cause analysis
5.  Repeat this process as often as needed until we are satisfied that TM3 is stable.
6.  Once stable migrate all projects into TM3 and kill off our old friend TM2

Cheers
Iain

**Comment by pgiraud** [comment]
I would rather remove the 1, 3 and 4 steps
I'm confident with the fact that TM3 will handle the load.

**Comment by bgirardot** [comment]
@pgiraud and @hunt3ri Very helpful. Thank you very much.

I still need to digest this a bit.

For sure we do not want to lose what TM2 has in the database.

**Comment by smit1678** [comment]
@bgirardot I concur with @pgiraud and @hunt3ri. Running in parallel for an extended period of time seems like a lot of extra overhead. I wouldn't full launch before it's been tested. 

I would recommend we do a period of testing with real projects and people with a soft launch. TM3 soft launches to test with specific projects. We run an extended period of time where specific project managers run their new projects on TM3 to test and ensure edge cases have been ironed out. 

If we're extremely worried about load, do some additional load testing with realistic numbers

Then switch over with the strategy of redirecting and monitoring closely.

**Comment by david-hotosm** [comment]
@bgirardot I agree with @smit1678, @pgiraud, and @hunt3ri. Lets oversize the servers for 12/24 and monitor. ElasticBeanstalk allows us to upsize or downsize as necessary with no downtime.
