### ISSUE TITLE
Display project categories on project detail page

### ISSUE THREAD

**Issue by Aadesh-Baral** [hotosm/tasking-manager#5734]
Currently, project managers have the ability to assign categories to their projects, however, these categories are not visible on the project detail page. By displaying project categories on this page, project managers will be able to more accurately categorize their projects, and contributors will have access to important information about the project's categories that they are contributing to. 

Also moving forward with the project recommendation system, having accurate project categories will be critical in suggesting the most relevant projects to users.

Suggested implementation:
Adding the project categories just under permissions section.
![Add a heading](https://user-images.githubusercontent.com/67958673/234550883-1e3febd3-5207-46eb-90b0-c0e8211a502f.png)

**Comment by HelNershingThapa** [comment]
Following our discussion on the call regarding the issue, here's the screenshot for category information alongside the campaigns and country. 

If there are two categories:
![categories](https://user-images.githubusercontent.com/51614993/235645609-290ad37c-38f2-4a49-9572-7790e1e5e2e5.png)

If there are more (nine) categories:
![morectg](https://user-images.githubusercontent.com/51614993/235645802-d59a6d84-7e84-47ca-818b-18742aa2bada.png)

cc @ramyaragupathy @d-rita @Ichchhie @Aadesh-Baral

**Comment by ramyaragupathy** [comment]
@HelNershingThapa - thanks for capturing the options visually.

I would want to the metadata field separate by a dot and if there are multiple options for the same metadata they should be either hyphenated or separated by a comma.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/12103383/236748096-b5a9168a-cf18-40b9-8dc7-88d45ac8434f.png">

Otherwise with multiple options, just a dot separation on all the options is confusing data for an end user.
