### ISSUE TITLE
Project Creation - Max task squares limit problem

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#579]
@feenster 

Given that the current functionality grids the bounding box of the aoi and not just the aoi itself, it makes it impossible to get the needed size of task squares because the task square count of the total bounding box is used, not what will end up being the trimmed number of task squares.

I think the quick fix it to just make the maximum number of task square pretty high or remove the hard limit and just give a warning.

![2017-06-16_16h27_29](https://user-images.githubusercontent.com/265831/27230840-ec3bf24e-52b0-11e7-9f7b-d31a50f43868.png)

**Comment by feenster** [comment]
The real hard limit here is that there is a 1GB limit on posting data to the server (this is an aws limit rather than anything configured within theTM3 application). With the current functionality, when gridding an AOI, the client app creates the task squares, then posts the AOI + tasks to the server for trimming, and for creating the project.  If the the size of the AOI + the tasks is greater than 1GB the server will respond with a 413 request entity too large.  The task square limit was imposed to mitigate this by making it less likely that the 1GB limit will be reached.  While increasing the task square limit will help in some cases, it will make it more likely that the 1GB limit is reached in other cases.  There is no hard and fast rule, it depends on the complexity of the AOI + the number of tasks created.

I see 3 options, but there may be others:

1. Increase the task limit and see how it goes..  Easy fix, but will make it more likely that the 1GB limit will be reached in certain scenarios.
2. Increase the 1GB limit on the server.  Not recommended as we should be keeping projects to a manageable size.  Risk that this cannot be configured in amazon anyway.
3. Move grid creation to the server.  This is the recommended solution.  Although the 1gb limit would still apply, it would be easier for users to work with as it would apply to the AOI only, since only the AOI needs posted to the server.  This will involve a non trivial refactor of existing client and server code.

**Comment by bgirardot** [comment]
Could we just grid the actual aoi instead of the bbox of the aoi?

**Comment by feenster** [comment]
We've tried that.  With bigger AOI's involving lots of task squares, Turf.js grinds to a halt as it tests each task  square to see if it intersects the aoi.

**Comment by bgirardot** [comment]
Does it really get anywhere near a 1GB even for lots of task squares?

**Comment by feenster** [comment]
Aggh, MB, not GB!  The limit is 1MB.  Sorry.

The attached file would do it if you went to a task size of 0.36 km2.  This creates a POST data size of 1.6MB.

![image](https://user-images.githubusercontent.com/16537909/27287754-9fc5b1ae-54fc-11e7-9dc6-68b1072bd35a.png)




[dissolved_large_aoi.zip](https://github.com/hotosm/tasking-manager/files/1085061/dissolved_large_aoi.zip)

**Comment by bgirardot-np** [comment]
That is good news, thank you for looking into it. @david-hotosm Can you get this incorporated into the deploy process?

**Comment by david-MIAW** [comment]
@feenster I see that thinkWare has an [example ElasticBeanstalk nginx config](https://github.com/hotosm/tasking-manager/edit/develop/.ebextensions/https_config.example) committed to the repo. Could your team setup the nginx rule that allows for the larger `client_max_body_size`? This is the first time I've worked with ElasticBeanstalk.

**Comment by david-hotosm** [comment]
@feenster I see that thinkWare has an [example ElasticBeanstalk nginx config](https://github.com/hotosm/tasking-manager/edit/develop/.ebextensions/https_config.example) committed to the repo. Could your team setup the nginx rule that allows for the larger `client_max_body_size`? This is the first time I've worked with ElasticBeanstalk.

**Comment by feenster** [comment]
https://github.com/hotosm/tasking-manager/issues/594#issuecomment-310401307

**Comment by hunt3ri** [comment]
Hi @bgirardot @david-hotosm 

I've tweaked the config in https://github.com/hotosm/tasking-manager/blob/develop/.ebextensions/environment.config to increase the timeout to 3 minutes and the max request size to 10MB

In local testing we managed to create and clip a 1.7Mb grid with over 4000 tasks which seems insanely huge.

@david-hotosm be aware that you will have to extend the timeout on the EC2 loadbalancer in front TM3 to 3 minutes to take advantage of this, otherwise Amazon will kill the request after 1 min.

Thanks

**Comment by bgirardot** [comment]
This is still a potential problem. I tried to create a pretty reasonable project that consisted of about 10 small AoIs spread over a moderate sized area and was unable to create small enough squares because the full bbox the individual aois covered was large.

I wonder if this issue is the reason @pgiraud created an outline of project areas in the TM2 to help with this issue.

Attached is the file i was trying to create a project for.

[mosul-dam-area-final.zip](https://github.com/hotosm/tasking-manager/files/1267402/mosul-dam-area-final.zip)

**Comment by willemarcel** [comment]
TM4 defined a limit on area and geometry size.
