### ISSUE TITLE
Create Campaign pages 

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#583]
This would allow a custom text field describing the campaign,
A dedicated page for the campaign based on the campaign tag would display the campaign description and all the projects tagged with that campaign tag.

**Comment by dalekunce** [comment]
@bgirardot just a heads up for others that may be working on this that Red Cross is going to take this and submit some code soon.

**Comment by verdy-p** [comment]
I hope this will allolw easier selection of existing Campaign Tags: instead of being free text, they should be associated with a complete object that can eventually be renamed. Existing projects with existing Campaign tags should have a default Campaign object prefilled (which will need to be edited with more useful info).

The same should be done for "Organization tag", with a plain "Organization" object that can be selected correctly instead of being created on the fly randomly while entering a new tag on a project. Some existing tags will need to be adjusted (projects will need to be merged to another more accurate Tag linked to a true Organization or Campaing object).

Additionally we should be allowed to have multiple Organizations endorsing the same projects and multiple parallel campaigns. Campaign objects or Organization objects should have essential info: leaders with some privileges, approved members, contact info, candidate members or participants, and list of endorsed projects, and their own priority assessment for any project they endorse.

When viewing a project that has been endorsed in a Campaign or by an Organization this should be visibvle in projects with their respective assesment: this would help fixing the real priority of projects (that they may not have created themselves but could still be created by any user of TM, or edited by any one with project admin role)

As well we'll be allowed to view a project list in a page for each organization (sorted according to their own priority assessement), or for each Campaign (also sorted with its own assessment for that campaign). The current priority is just a default one when viewing the full list of projects (even if we select some filters by organization or campaign).

The difficulty and state (draft/published/archived) of a project however is global for all campaigns or organizations, but some organizations or campaigns may want their own assessment/review of completed projects before they archive them (for stopping folllowing them if their need is already satisfied), or stop supporting it (when they no longer need the completion of the project because they're working on something else better for their needs, possibly in another more focused area or with more specific mapping goals and instructions in a new project they create themselves).

**Comment by bgirardot** [comment]
Just adding this as I had to create this by hand and it would be really good if we some way to generate searches for projects, campaign based or not, and display them and their status on a map.

![2018-04-06_15h03_37](https://user-images.githubusercontent.com/265831/38435505-180784f2-39d2-11e8-8287-0f30ed5bc3c3.png)

**Comment by mikelmaron** [comment]
> Red Cross is going to take this and submit some code soon.

@dalekunce can you point us at the PR?

**Comment by xamanu** [comment]
This is related to #1590, where we are rethinking campaigns a bit. As a result pages for campaigns shall be created, too, this this issue being tackled.

**Comment by jarmokivekas** [comment]
I know this is starting to be an old issue, but similar to what @bgirardot pointed out, it would be nice to be able to see all TM projects that belong to a specific campaign in a single map. I've been using uMap for this, but keeping the uMap up-to-date with the projects is a little tedious (and prone to error)

 http://u.osmfr.org/m/354400/
![image](https://user-images.githubusercontent.com/3074453/62958805-287bf300-be00-11e9-8ae4-76bbd6ca1585.png)

The Map View in the TM search is a step in the right direction. Something similar which shows the project AOI/task grid would be brilliant.

![image](https://user-images.githubusercontent.com/3074453/62959209-eb643080-be00-11e9-9a4e-ea4daf3b6f60.png)

**Comment by xamanu** [comment]
This is becoming even more interesting with the improvements for campaigns in TM4. Moving this to our roadmap.

**Comment by ramyaragupathy** [comment]
Closing here as we have a campaign page setup and the campaign summary can be tracked in a separate ticket https://github.com/hotosm/tasking-manager/issues/583
