### ISSUE TITLE
[BUG] Specific instruction text appears to disable task editing

### ISSUE THREAD

**Issue by jeffreyameyer** [hotosm/tasking-manager#5902]
**Describe the bug**
Using the OHM Tasking Manager at [tasks.openhistoricalmap.org](tasks.openhistoricalmap.org), when I created a project with [this text](https://gist.github.com/jeffreyameyer/1047404c18f1121e0c540f7083189c35) in the Instructions field, when a user would try to select a map, they would see a brief flash of something, then they'd be told that task was locked. Then, there'd be no way to access that task in order to unlock / complete it & no amount of task resetting or validation seemed to be able to fix this user and task lock.

<img width="1680" alt="Monosnap #35: DO NOT USE - test project - OHM Tasking Manager 2023-06-10 11-30-51" src="https://github.com/hotosm/tasking-manager/assets/1494546/de5221ca-2705-4ced-9386-2d32387b7b2a">

**To Reproduce**
1. Go to https://tasks.openhistoricalmap.org/projects/35
2. Log in
3. Click on Contribute
4. Click on "Map a Task"
5. See error

**Expected behavior**

I would normally expect "Map a Task" to take me to the iD editor zoomed to the bbox for that task.

**Desktop (please complete the following information):**
Tested across multiple browsers on Mac OS 13.4 Ventura.

**Comment by HelNershingThapa** [comment]
@jeffreyameyer Based on the information provided, your issue appears to be related to locking tasks and not the text in the instructions field.

The popover message you shared on the screenshot shows that you'll need to provide a status for the previous task you locked. This is required to continue mapping the task you want. When you try to map another task without providing any status for the last locked task, you receive the error message and cannot proceed.

You should click the "Map that task" button to resolve this. This will take you to the task action page of the task you previously locked. On this page, you can provide the status of the task. Once you provide the status, you will be redirected to the task you initially wanted to map, and you should be able to proceed without any issues.

**Comment by Aadesh-Baral** [comment]
@jeffreyameyer Thanks for reporting the issue.
I did some investigation and found out that the issue occurs when there are unclosed curly curly bracket like `{`, `}` and empty curly curly brackets like `{}` instead of curly curly brackets with at least one character in the specific tasks instruction. This causes the endpoint `users/queries/tasks/locked/details/` to fail, resulting in a fallback error dialogue being displayed on the frontend.
Specific task instruction is formatted on backend to replace {x}, {y} and {z} with tasks specific x, y and z values. So while performing this formatting if  `{`, `}` or `{}` is encountered it throws an error. We need to update the endpoint so that it returns the text as it is if it encounters error while formatting the text.
