### ISSUE TITLE
Default changeset tags not showing in project creation

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#5907]
Project managers reported that the default tags were not displayed in the project edit/creation page. They have also confirmed that while mapping, the tags are being propagated, so this is likely a frontend bug. 

This will likely cause confusion for PMs, so it would be good to prioritize.

**Comment by HelNershingThapa** [comment]
After investigating the issue with @Aadesh-Baral, the problem appears to be due to a mismatch between the `TM_DEFAULT_CHANGESET_COMMENT` environment variable value used in the front end and the back end. This mismatch causes the front end to expect a different _pattern_ for the default changeset comment compared to what is being generated by the backend during project creation.

It is essential to ensure that the `TM_DEFAULT_CHANGESET_COMMENT` environment variable is consistent between the front and back end. This will ensure that the _pattern_ matches the default changeset comment generated by the backend. For example, if the value of `TM_DEFAULT_CHANGESET_COMMENT` is set to `#hotosm-project`, then the project's default changeset comment will be set to `#hotosm-project-XXX`. But say the frontend environment variable has `TM_DEFAULT_CHANGESET_COMMENT` as `#hot-project` (or a mismatch), then the frontend expects the default changeset comment to be in the pattern of `#hot-project-XXX`. And this mismatch has caused the input field to be empty, which is the issue.

**Comment by Jorieke** [comment]
For new projects there is no #hotosm-project-XXX added. It adds very weirdly the word "undefined" instead.

**Comment by dakotabenjamin** [comment]
It's a bit of a risk to have to set the variable twice in deployment (once in the backend via cloudformation, another time in the CI context for frontend) so could we make some changes to deployment workflow to ensure consistent setting of variables
