### ISSUE TITLE
Infinite split

### ISSUE THREAD

**Issue by pgiraud** [hotosm/tasking-manager#594]
Currently in TM3 the splitting feature has no limit. It can be a project manager during project creation or a mapper when a task is selected for mapping.

![capture du 2017-06-21 08-58-46](https://user-images.githubusercontent.com/319774/27371155-df499d7c-565f-11e7-8191-b2913294de8d.png)

In TM2, for gridded projects we were storing the zoom at which the tasks were created and using it to compare with the tasks' zoom. Users were allowed to split only two times.
Also storing a zoom level in the project itself were useful to tell whether a project was gridded or arbitrary afterwards. Useful for per task instructions for example.

**Comment by feenster** [comment]
@pgiraud there are few things to consider here.  

It should be noted that grid creation and task splitting at the project create stage happens on the client, while arbitary task creation and splitting a task while mapping happen on the server.

If you want to store the original zoom level for the tasks for a project, you would need to refactor the client to track the the project zoom level and then pass it in to the PUT admin/project api at the create project step.  

As you note, It is now possible in TM3 to split tasks in the project creation wizard.  This would have to be considered.  Should the 2 split limit apply here too?  If so you would need to implement that client side.

A first step could be to refactor the project creation wizard to move grid creation and task splitting to the server.  That would be a fairly non trivial refactor however, but there are already other drivers for doing this as well (https://github.com/hotosm/tasking-manager/issues/579#issuecomment-309384238).  

That would obviously change things again for this requirement but possibly make it easier to do.

**Comment by bgirardot** [comment]
Would the limit on splitting be possible or make more sense to just set a minimum size for a task square?

Like ~3m ?

Then we are not counting or caring when it was split etc.

If possible a minimum size might be the best option.

I think it is an improvement to allow unlimited splits, we get a lot more flexibility in project creation and it allows for making less well created projects more usable.

Some of our projects start out with way way too big task squares and only being able to split them twice only gets you down to 'too big' sized tasks squares.

**Comment by feenster** [comment]
Yes I think if you did want to limit splitting, using an absolute minimum area, rather than a number of splits would be easier to implement.

**Comment by pgiraud** [comment]
If you have to split several times (more than 2) to get a square of the correct size, this in my opinion means that the initial grid size was incorrect. Which eventually means that all the squares in this project should be divided into smaller pieces.
I agree that limiting by the size would be a bit easier. Not that much though.

By the way the ability to split tasks during project creation is a really nice addition.

Again, splitting more than twice (or three times maybe) means wrong initial size.
I don't want to bother more on this one if it requires a lot of refactoring.

@feenster any reason why you chose to manage the grid creation client-side?
Did you see any performance issue at this point in TM2? I agree that TurfJS is super fast for that.
Or is it to ease the "split while creating"?

**Comment by feenster** [comment]
@pgiraud we didn't see any issues with TM2 here.

We thought that doing the grid creation, resizing and splitting 100% client side then doing one PUT at the end with the final grid would be easier and better than doing multiple server api calls and persisting temp grids server side during project creation.  It was fine with a single feature AOI, but with large complex multi part AOI's turf.js would grind to a halt when trying to throw away squares that didn't intersect the AOI.  Our solution was to create an initial grid to the full bounding box and do all the task splitting and sizing on the client, (which turf could handle well), then have the trim/clip (which turf could handle well) part happening on the server.  The split during mapping was done server side because for that, actual project tasks and task history would have to be created/deleted updated to reflect the task being split.
