### ISSUE TITLE
Make the 'Advanced search options' more eye-catching

### ISSUE THREAD

**Issue by felix-yew** [hotosm/tasking-manager#595]
We need to use another option for help the user if want to use the sort/searching task by mapping difficulty and maybe priority for mapping (like suggestion from this ticket https://github.com/hotosm/tasking-manager/issues/584).
![image](https://user-images.githubusercontent.com/13621886/27377224-985fa430-569e-11e7-9dda-9d3e8f843b97.png)
If you still want to use the existing sentence, then please be more clear for the color (not so soft) and/or made more thick the letter.
Or, maybe we can add an icon, for example like in office software ![image](https://user-images.githubusercontent.com/13621886/27377595-9bf01f34-569f-11e7-8b63-1ea11df128f1.png). It will helpful for the user to find what they need to sort/search the task that they want, whether they need by mapping difficult or priority or something else.

Cc: @bgirardot  @fredychandra

**Comment by bgirardot** [comment]
Hi @felix-yew I am closing this because we re-did the UI significantly and this is hopefully addressed.

Please have a look at the new UI and if you still have issues (I am sure you will, we all do :) please see if there is an existing issue you can +1 or create a new issue.

Thank you for helping get this launched, this feedback was part of what made us decide to re-do the UI.

Respectfully, blake
