### ISSUE TITLE
Contribute - Validate - Task history not clear who marked it done

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#620]
We should change "Mapped by" to "Completed by" so it is more clear who marked the task complete.

**Comment by hunt3ri** [comment]
We've used the term "Mapped" throughout the application because locally users were confused by tasks marked as complete when they weren't actually complete, eg they still needed to be validated.

So a task is now  Mapped By User A and Validated By User B.  Which is hopefully clearer.

**Comment by feenster** [comment]
As Iain says, we've used the term 'Mapped' for the status, and that term has been used in a number of places: map legend, stats, activity, history, action buttons and calls to action text,  While this would be technically easy to do, we would advise strongly against introducing different terminology for the same status throughout the application.  We suggest this would introduce confusion and inconsistency.  There may be other ways to meet the requirement, such as simply making the 'Marked as mapped' history stand out more visually.  

Perhaps consider the underlying user story using the following template:
As a.....
So that.....
I want.....

E.g. as a validator, so that I can decide whether to checkout the task for validation, I want to easily see who marked a task as mapped.

**Comment by xamanu** [comment]
This is to be considered in the ongoing redesign with @hotosm/major hotosm/projects#24

**Comment by xamanu** [comment]
This is now shown on TM4.
