### ISSUE TITLE
JOSM hand off for mapping creates new data layer every time

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#637]
When handing off to JOSM during mapping, one task at a time, a new data layer is created every time. Ideally it would not create a new data layer every time.

**Comment by nomoregrapes** [comment]
JOSM has a preferences setting (under remote control, download objects to new layer), but HOT tasking manager doesn't care that it's unticked. Which would make me want to label this as a bug rather than a refinement.

Work around: in the JOSM preferences tick "Confirm all Remote Control actions manually". If you can understand the popups, you can say **no** to the one that creates a new layer (I think it will say `"wants to add the following data: ?xml version="1.0"`) but say **yes** to loading data from a specified bounding box.

**Comment by willemarcel** [comment]
I think it was solved with the recent implementation of multiple tasks validation.
