### ISSUE TITLE
Serve TM3 over HTTPS

### ISSUE THREAD

**Issue by hunt3ri** [hotosm/tasking-manager#639]
@david-hotosm @bgirardot @smit1678 

I'll be looking at the nginx config over the next sprint, are you guys thinking of serving the new TM3 over HTTPS, as I could advise how to set that up.

Thanks

**Comment by david-hotosm** [comment]
@hunt3ri yes. HTTPS would be preferred. Would you terminate HTTPS at the ELB? I'd prefer to use LetsEncrypt for anyone running TM3 outside of Elastic Beanstalk. What are you thoughts?

**Comment by hunt3ri** [comment]
Yes definitely terminating at the ELB of it's a big headache in the app.

When I've done this before I've used the AWS Certificate Manager to create an HTTPS cert that you can very simply add to your HTTPS endpoint on the ELB,

**Comment by sjparkinson** [comment]
I'd opened an issue on the old task manager regarding `https://` support, and just wanted to re-open it here.

https://github.com/hotosm/osm-tasking-manager2/issues/988

> Currently the main site only works over plain text, while OpenStreetMap works over TLS.
> 
> As described in openstreetmap/iD#3771, this is causing a mixed content warning when using the iD editor for loading boundaries.

```
Mixed Content: The page at 'https://www.openstreetmap.org/edit?editor=id&#map=18/-18.7024446936/30.4725…' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://tasks.hotosm.org/project/3182/task/669.gpx'. This request has been blocked; the content must be served over HTTPS.
```

> With free services like Let's Encrypt and CloudFlare, it'd be great to serve the site with a certificate.

This was because I use an extension called HTTPS Everywhere which has rules for Open Street Map.

Worth pointing out that the session cookie is currently being passed over plain text, and I'd guess also the oauth token returned from the Open Street Map login.

Trivial to capture at mapathons using unsecured WiFi access points. All good reasons why the site should be https:// only.

**Comment by bgirardot** [comment]
@david-hotosm @smit1678 Can we move on this? I guess it is causing issues with the iD editor that we are not all https + other reasons listed here.

**Comment by hunt3ri** [comment]
As I mentioned above now the app is being served entirely out of AWS it's very simple to use the Amazon Certificate manager to set up HTTPS.  Give me a shout if I can help

**Comment by smit1678** [comment]
@bgirardot Yes, this should have been done from the beginning. Will sort this out via #sysadmin on Slack.

**Comment by ethan-nelson** [comment]
This is now deployed! Thanks everyone for input and help!
