### ISSUE TITLE
Design improvements to statistics elements in partner pages

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6473]
Per discussion w/ @emi420 @royallsilwallz design for partner pages should be consistent with the rest of the statistics page.

![image](https://github.com/hotosm/tasking-manager/assets/12103383/9d04632d-ae3a-4f7e-a1d9-bf1899975bc1)

cc @manjitapandey

**Comment by emi420** [comment]
What do you think about this proposal?

@ramyaragupathy @royallsilwallz @manjitapandey 

![tm-leaderboard](https://github.com/hotosm/tasking-manager/assets/1226194/9af47011-4f40-4502-9db7-d9de6837e281)

**Comment by royallsilwallz** [comment]
This looks really nice @emi420. I'm just concerned about the black background on the logo. What if the logo is black?
And the theme in  Activity section also doesn't go well with the HOT red theme.

**Comment by emi420** [comment]
Great @royallsilwallz ! the black/dark grey background is what's used currently for the Missing Maps leaderboard, so we'll be good with that. For the Activity section, yeah maybe, I've used the same HOT theme colors. Thanks for the feedback!

**Comment by ramyaragupathy** [comment]
@emi420 - thanks for improvising this.

* we shoudl include primary hashtag right below the logo or somewhere in a striking position
* agree with the stance on black background for logos
* resources section could go above activity for better information discovery, since there could be links for support, registration, connecting via teams and so on. 

cc @royallsilwallz @manjitapandey

**Comment by emi420** [comment]
@ramyaragupathy thanks for your feedback!

- Yes, I wasn't sure if it was needed, I'll add it and post another proposal.
- I will also move the resource section to another place, maybe to the header because I feel that it get lost between the two blocks of stats.
- The dark background is to give the feel that this is a special page, kind of a landing page for the partner. Furthermore, the same background is being used on the current [Missing Maps leaderboard](https://www.missingmaps.org/partners/accenture/) and in the Tasking Manager home page.

<img width="807" alt="Screenshot 2024-07-01 at 10 30 17" src="https://github.com/hotosm/tasking-manager/assets/1226194/9a0d12b9-6b94-4c60-ae2a-88bf34323380">

Logos are often designed in a way that works fine in dark or light backgrounds.

CC @royallsilwallz @manjitapandey

**Comment by emi420** [comment]
New version:

* Hashtag was added in a striking position
* Resource section was moved to another place

![tm-partners-design-v2](https://github.com/hotosm/tasking-manager/assets/1226194/8e715590-d1bd-49e4-a2a7-b8b54563264a)

CC @ramyaragupathy @manjitapandey @royallsilwallz

**Comment by manjitapandey** [comment]
Looks Better @emi420 , But we provide 5 more link options in addition to meta, X and instagram link. If user uploads more links to the page, it may look congested. 
Also can we go with HOT theme background for activity section or other shades of blacks little different? because we have white text on lighter background of activity bar causing difficult to user to visualise.

**Comment by ramyaragupathy** [comment]
@emi420 - like the placement of social icons on top right and the highlight on primary hashtag. Thinking if we could reduce it to smaller icons instead of buttons. We could restrict this to just three icons in the same placement that you have proposed. Same format is followed in our website as well.
<img width="166" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/3399af29-5319-4f9e-980d-a3400dad9a2a">

Rest of the five custom links could be termed `resources` and they move right above the` activity` section and below the `current projects` section. And these could follow the outlined button styled approach that you have used for social icons. That way the information is balanced. Social media links get the attention that it wants and the  discover time for resources links is also quick.

Please let me know your thoughts.

cc @manjitapandey @emi420

**Comment by ramyaragupathy** [comment]
<img width="1363" alt="image" src="https://github.com/hotosm/tasking-manager/assets/12103383/d2b28228-5edd-447b-8cbf-2fd2af50a714">

Also flagging to include information on stats source for the user to refer to.

cc @royallsilwallz @emi420 @manjitapandey
