### ISSUE TITLE
scripts/docker/Dockerfile.backend deprecated?

### ISSUE THREAD

**Issue by frafra** [hotosm/tasking-manager#6552]
Shoud scripts/docker/Dockerfile.backend be deleted, since the compose file uses the `Dockerfile` in the root of the project?

**Comment by ramyaragupathy** [comment]
cc @mahesh-naxa @spwoodcock

**Comment by spwoodcock** [comment]
Thanks @frafra!

Related to https://github.com/hotosm/tasking-manager/pull/6436 which updated `scripts/docker/Dockerfile.backend` instead of `Dockerfile`.

I was under the impression that the deployments for TM in AWS are not using Docker anyway.
The docker setup is only for local development currently. Is this right @dakotabenjamin?

If so, we can delete `scripts/docker/Dockerfile.backend` as mentioned, as it's a duplicate 👍

**Comment by dakotabenjamin** [comment]
@mahesh-naxa which dockerfiles will you be using for containerization?

**Comment by frafra** [comment]
I mean, `scripts/docker/Dockerfile.backend` is not even working with the current compose, because the healthcheck requires curl, and without curl the healthcheck fails and traefik does not forward the connection to an unhealthy container. This has been fixed on the main Dockerfile, but not on `scripts/docker/Dockerfile.backend`. The other option would be moving `Dockerfile` to `scripts/docker/Dockerfile.backend` and keep all dockerfiles there.
