### ISSUE TITLE
Unable to migrate DB after create

### ISSUE THREAD

**Issue by olearytd** [hotosm/tasking-manager#665]
I'm trying to stand this up locally and everything is good until I get to the DB migrate step.  I have my environmental variables set up in my ~/.bash_profile

I've tried making the postgresql database on my own and following the Docker instructions found here:
https://github.com/hotosm/tasking-manager/wiki/Dev-Ops#creating-a-local-postgis-database-with-docker

The database is created in both instances but when I run the update I get the following error complaining 
`column "tsv" of relation "project_info" does not exist`

I'm assuming this is because the db is empty and doesn't have the schema required by tasking-manager.

Is this a correct assumption?  How do I init the schema to the db?

I apologize if this is already answered, I couldn't find an existing issue or anything in the README.md

Thanks!

**Comment by olearytd** [comment]
I didn't check closed issues, this may be related:
https://github.com/hotosm/tasking-manager/issues/404

Going to go through the ticket and see if it helps me out.  I'll close if so

**Comment by bgirardot-np** [comment]
Hi @olearytd I can't comment on this specific issue because I do not use the docker deployment method.

I generally do mine all via command line using the wiki entry on this repo for "client install ..." which actually works for both the client and the server.

Please let us know if you can not get it working.

**Comment by olearytd** [comment]
The above issue doesn't look to be the same as I'm seeing.  Please let me know if you've run across this before, thanks! 👍 

If it helps I'm running on Centos7

**Comment by bgirardot-np** [comment]
@david-hotosm Any ideas?

**Comment by mathcass** [comment]
Hi @olearytd, out of curiosity, I took a few moments to try out the instructions in the README (it was a good exercise to finally try setting up the task-manager) and I can report that the instructions worked for me using the Docker container for Postgres. 

---

A question, though, if I might ask. What git commit are you on right now? I pulled the latest and I'm on this one: 


```
$ git rev-parse HEAD
56d1d13056bbea342132cf6e78b12f01c73d5dd3
```

I asked because the error you're getting references a field `tsv`, which looks like was fixed in this changeset, 42a2a77c6491581f66962a76e09deaa4f6468e4d. Are you getting a similar issue on a more recent changeset at all? 

---

I figured I'd pop in and comment on what I found, in case it helped. Cheers.

**Comment by olearytd** [comment]
Thanks for the replies all!

I will double check my commit and try again

**Comment by olearytd** [comment]
@mathcass I'm going to close the ticket, testing the latest develop I didn't have the issue.  Thanks for pointing out I needed to just do a simple update 😆

**Comment by mathcass** [comment]
No problem @olearytd. :) Always happy to [rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging) an issue with someone.
