### ISSUE TITLE
Logos in about page won't show when running an ad-blocker

### ISSUE THREAD

**Issue by cgiovando** [hotosm/tasking-manager#702]
In OX 10.11.6 / Chrome 60.0 when an ad-blocker is installed (uBlock Origin v1.13.8), logos in the [About page](http://tasks-demo.hotosm.org/about) do not show.

Is there a way to embed them similarly to images on the homepage (with simple HTML), so that ad-blockers don't interfere with them?

**Comment by bgirardot** [comment]
@LindaAlblas The issue seems to be the css class "sponsor-logo" and the EasyList adblocking list.

It looks like "supporters-logo" would work instead for the class name for EasyList at least.

I don't feel comfortable editing classes yet, but I find that blocked text in these files:

app/about/about.html
assets/styles/sass/_about.scss
assets/styles/css/taskingmanager.css

![2017-08-25_15h11_42](https://user-images.githubusercontent.com/265831/29716002-f0e7d5b2-89a9-11e7-8cbb-58999031fb09.png)

**Comment by LindaAlblas** [comment]
@bgirardot interesting. I'll change the CSS class if you are able to test it then?

**Comment by bgirardot** [comment]
@LindaAlblas Can do.

Sorry I know it seems simple, but I don't want to mess with stuff I don't understand fully, especially at the moment.

**Comment by LindaAlblas** [comment]
@bgirardot no worries!

**Comment by bgirardot** [comment]
@cgiovando this should be fixed now, please let us know if it is not.

deployed to tasks-stage.hotosm.org

you might have to "shift" reload to get everything.

**Comment by cgiovando** [comment]
:+1:
