### ISSUE TITLE
100% mapped and validated

### ISSUE THREAD

**Issue by tastrax** [hotosm/tasking-manager#713]
TM3 - On the map interface there appears to be quite a few projects 100% Mapped and validated. I assume these should be archived in some way? It just clutters the map (and I assume the list view also).

**Comment by hunt3ri** [comment]
Yes @tastrax Project Managers should be encouraged to update these projects to Archived in the Project Management window.  This means they won't show up in search results, but can still be seen by PMs in their dashboard.

**Comment by ethan-nelson** [comment]
Right now this is a call that the project manager makes and I don't think we want to institute any automated archive procedures. I'm going to go ahead and close this, but thank you for all your feedback so far tastrax!

**Comment by verdy-p** [comment]
I also agree that sometimes a project may look 100% mapped and validated, but with some tiles recently marked as validated needing further checks and that may be in fact invalidated.
Even a validator may click by error on "mark as validated" and would want to reedit the tile immediately, which would be impossible if it was immediately "archived" (except by project admins that would first need to change back the status).
Given project admins will soon have the possiblity to explore all tasks (and that project authors already have the project listed in their dashboard), they should be able to monitor the current state of projects and make the necessary change of publication status.

But we could also have a notification sent by the Tasking Manager to project authors when any project gets completed, or had some changes since the last check: that notification would be sent at most once a day as a reminder of progresses or changes: these notifications would be listed in some event history list of the author's dashboard (possibly cumulating multiple events in that history: the author's dashboard already lists projects, they can have a "last event" date column with a link to show proeminently the history of a project for reviewing what occured there (user X completed task #n, user Y validated tile #n, project now mapped n%, project now validated n%, project created, project draft changed to published, published project changed back to draft, published project changed to archived, project description changed, priority area modified...)
