### ISSUE TITLE
Missing Maps Badges

### ISSUE THREAD

**Issue by dalekunce** [hotosm/tasking-manager#744]
A coming feature of the Missing Maps Leaderboards will be to able to embed the badges earned.

This should be included in the user profile page in the TM.

**Comment by tastrax** [comment]
Missing maps badges link looks to be in TM3 under user profile however the URL is incorrect

http://www.missingmaps.org/users/#/USERNAME/history - this fails

should either be 

http://www.missingmaps.org/users/#/USERNAME or
http://www.missingmaps.org/users/#/USERNAME/badges

**Comment by bgirardot** [comment]
@tastrax Thank you very much for looking at this. I have notified @dalekunce  who made the pull request #743 that added it. I am not sure if the url is for functionality that is coming to the MM website, or it needs to be changed to match how the MM website works now.

**Comment by geofrizz** [comment]
Some problems also with the username!
In MM website if you search directly the user profile, the username is converted in lowercase for the url.

In TM3 the link use the right format of the user name, but the result don't found the user.
http://www.missingmaps.org/users/#/GeoFrizz

For MM website the right format is:
http://www.missingmaps.org/users/#/geofrizz
All username in lowercase.

Mmmh !! Also the "space" is converted in minus sign ("-"), always on the MM site.

**Comment by dalekunce** [comment]
Looks like we got some more work to do on mm before we can take this live in the tm3. cc @mojodna

**Comment by verdy-p** [comment]
if there are other transforms, there should be a way to specify the username actually used on a the third party site (just like if we pair any site to our social network accounts). The usernames could be actually completely different.

The same occurs in OSM between the wiki user names and OSM user names, because they require separate registration and they don't support exactly the same constraints on user names (wiki user names have their initial capitalized but letter case is not significant on it, but OSM user names are fully case significant, and wiki users names do not distinguish spaces and underscores, and do not allow the presence of some other characters like "/" allowed in OSM user accounts...) And there's also a separate registration for the OSM help forum, also on a different server managed separately, and separate usernames for other internal services.

This is general: any third party site should have a way to connect them with their own separate account (note also that they may be subscribed by the same users using different email adresses, and their own local profiles may not show the same social network connections)

Here MissingMaps.org is a different party, independant of OSM, not all MissingMaps.org members are OSM members (the reverse being true as well). So don't assume usernames used there are the same.

Even each task manager instance could have their own separate registration.

Depending on which site you first start creating an account, the same account name may be already allocated to another unrelated user on the other, and so they won't match, and none of the site has the priority for reserving user names (and none should force their existing registered users to change their user name and break their own local history in contributions, talks, blogs and public profiles already communicated with their URLs on other social sites or organization sites).

So the long term solution is to add in TM a way to attach a local profile to third party sites with their separate user account (this can be used for various third parties, OSM-related or not, and give the separate option to make this public in their profile, or private for internal use by the user himself as a facility to navigate to from TM to their third party site or to read third party info to render on the TM site via the third party API we want to support in the TM website)

**Comment by ethan-nelson** [comment]
Here are the transform rules I could find on https://github.com/MissingMaps/users/blob/bd18d95e2946f1e42b3d7c604e7a417af78c3bf2/src/containers/Users.js

`  onSubmit: function (input) {
    var user = R.find(R.propEq('name', input.toLowerCase()))(this.state.users);
    if (user) {
      this.props.history.push('/' + user.name.replace(/\s+/g, '-').toLowerCase());
    } else {
      this.props.history.push('/' + 1);
    }
},`

Indeed, it may be easier to have people indicate their MM username (just like they can for LinkedIn or Facebook) instead of doing it automatically, depending on how that system handles a name change.

**Comment by dalekunce** [comment]
@verdy-p and @ethan-nelson I just want to clear one important thing up. If you are a "missing maps" user you are for sure an OSM one. We are not requiring people to register separately or have a different affiliation. In fact any that has edited since 2014 would most likely show up in our database which is just a copy of the users from OSM as they make the edits, taken from planet_history and changesets. Most of what you said @verdy-p is not accurate and does not reflect how the missing maps leaderboards and site actually work. I appreciate your time on this issue but please don't speculate on technical matters the way that you have without first looking at the code.

As @geofrizz and @ethan-nelson point out we only need to make a minor change in the way we process users for your OSM username to be consistent across the various OSM platforms.

cc @mojodna can you fix the regex for the username transform.

**Comment by verdy-p** [comment]
if you change/force the lettercase of usernames in MM, you are breaking the uniqueness or equivalence with usernames used in OSM, where they are fully case significant:
"verdyp" or "Verdyp" on OSM are not the same user account and can be registered by distinct users, the yare quivalent on OSM wiki but this causes similar problems so the lsit of users are not the same and require separate registration. In MM you are then assuming that case difference does not matter in OSM and this is wrong. You cannot warranty that they are controled by the same OSM user.
A simple "corrected" regexp transform will not fix the issue and people will need to adjust their user names on each system. There's simply no bijective equivalence when you use a lossy text transform that drops case differences.

**Comment by xamanu** [comment]
The continuation of badges is being discussed here: #1617
