### ISSUE TITLE
Metadata label and value not correctly aligned in project result

### ISSUE THREAD

**Issue by pgiraud** [hotosm/tasking-manager#757]
In contribute page, in the project results cards the list of metadata items is not correctly aligned.
![screenshot from 2017-08-29 09-35-04](https://user-images.githubusercontent.com/319774/29809738-94a9160c-8c9d-11e7-953d-65cac78b9ae6.png)

**Comment by alekno** [comment]
Is solved on working version. Can be closed.

**Comment by verdy-p** [comment]
this is in fact cause by the fact that the first part (dt) is a block with relative positioning (using also clear), anf the second part (dd) is positioned by a block with floating positioning (not using clear) the vertical alignment of margins and baselines never applies to floating elements: if the first part uses a different font size or line-height, the floating element will not align with it, even if there was a vertical "clear" in the container containing both.

I just wonder why the second part (dd) ever needs to use floating or even why it is a block element, when it should just be "display:inline", just like the first element (dt), both being part of a "definition list" where there's just the need to insert some spacing between both. HTML already natively offers a much better "compact" style lists instead of the default "indented" style for definition lists. The "compact" option do not require such horrible CSS tweaks like here where "float:left" is complete non-sense and will never line-up correctly the baselines and margins, notably if you cannot predict the font sizes used in separate "dt" and "dd" elements !

**Comment by alekno** [comment]
Indeed, lot of nonsense in the CSS elements. Not only in dt and dd. This needs someone with a CSS clue to fix. Someone tweaked a lot in the past, and made is worse.

**Comment by ethan-nelson** [comment]
I've tested this on a few computers and browsers and it looks to be solved. Please reopen if that is not the case.
