### ISSUE TITLE
Support GeoJSONs that are LineStrings

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#774]
At the moment, you can only create projects from geojsons that have objects of the type Polygon or Multipolygon.

Unfortunately JOSM creates LineString based geojsons often.

Turf.js supports http://turfjs.org/docs/#linestringtopolygon and http://turfjs.org/docs/#polygonize

It would be good if the TM3 could recognize a LineString geojosn and then make it a polygon internally so it could continue with project creation.

**Comment by verdy-p** [comment]
May be also MultiLineString to MultiPolygon.

Caveat: LineString's are not necessarily closed. If there's a single one, you can add an extra final node at end to close it (this is implicit with Polygons but not with LineString).

However OSM relations are sometimes exported (in JOSM) as MultilineStrings (one Linestring per member way) or geometry collections (including OSM nodes exported as Points) and often with additional features with duplicated geometry for each member way or node.

OSM relation with type="multipolygon" (or "boundary" ?) assume an area but frequently have memùber nodes (e.g. admin_centre or label in boundaries), so they cannot be safely exported as GeoJSON "MultiPolygon".

And in fact most OSM multipolygons should become "Polygon" in GeoJSON (only one "outer" ring of ways, possibly with some "inner" rings), and will require reordering the member ways correctly to form the closed ring(s). OSM does not restrict relations, it is left to the interpretation of other tags (including OSM tag "area=yes/no") to see if they designate a lines network, or a surface.

OSM relations with "type=multipolygon" generally imply a surface that should be completly delimited by member ways forming one or more rings (normally the OSM "inner" or "outer" roles should be set correctly for member ways but ways are frequently disordered by editors: before exporting an OSM relation as a GeoJSON, we frequently need to cleanup the member lists and reorder it, putting all "outer" rings first, but it's difficult to sort "inner" rings after each "outer" ring" in which they are present (but this is a requirement for GeoJSON where all rings must be properly ordered, and inner rings absolutely be associated to the specific outer ring within which they create holes).

So OSM relations are difficult to handle. This is still a constant need for creating TM projects, when users will frequently want to be able to select one or more "boundary" relations (they can have holes and can have multiple exclaves forming multiple outer rings).

----

We still lack a coherent editor that will enforce the GeoJSON geometry requirements for [Multi]Polygons but will not necessarily need to discard the node members ("admin_centre" or "label") or reorder them (reordering nodes can alter the meaning in some cases, such as transport routes, which may still contain polygonal entities such as buildings: I suppose that TM projects will not need to be created for these linear features and that preparation of geometries in JOSM will be done without submitting to the OSM server).

Still JOSM will save the GeoJSON as part of a FeatureSet, with one feature per OSM object that has tags (it just does not export nodes as "Points" in GeoJSON if these nodes have no tags or these tags are metadata and discardable such as "created_by=*", or ignorable (but member nodes used as admin_centre or label are not discardable, just like member nodes for stop position and platforms in routes)

We should have the possibility in JOSM to work in a pure "GeoJSON" layer which will never assume the OSM relations and where there are true properties and not OSM tags. Instead of saving OSM data to GeoJSON, we would select objects to put in a GeoJSON layer that will never be submitted directly to OSM before it has been reimported into a OSM layer (the conversion GeoJSON to OSM is much simpler than the reverse, but will create new OSM objects that could duplicate those in OSM datatabase if they are submitted from such imports).

JOSM should still be able to submit a GeoJSON to a GeoJSON database (not the OSM db) along with properties as a FeaturesCollection: it is useful to work with many GIS database. And most exports from OSM are converting OSM data to classic GIS geometries (as shapes or GeoJSON), including exports made by renderers.

**Comment by ethan-nelson** [comment]
Here is some starter code if anyone is interested: https://github.com/hotosm/osm-tasking-manager2/blob/master/osmtm/static/js/project.new.js#L151-L166

**Comment by willemarcel** [comment]
TM4 supports closed LineStrings
