### ISSUE TITLE
Project Creation - splitting keeps splitting after hitting 'next'

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#775]
When I split by point or polygon, even after I am done on the following screens it keeps the split pointer and still allows splitting, even after trimming. Same for by point or by polygon.

**Comment by verdy-p** [comment]
If we "trim" the project area, after selecting the default subtiling size, the generated project will have some bordering tiles that are not full quad tiles.

These tiles then will no longer be splittable at all even if they are large enough for the next tiling level (zoom level of internal "quads"). Subtiling should be able to split a tile on any horizontal or vertical dimension when the current tile's bounding box is larger than half the current quad width/height.

this means that in some cases a bordering tile will be splitted only in 2, not four. If the current tile's width is > 50% and <=75% of current quad size, it will be splitted in two but not along the half quad size (instead use internally subdivide in 4, and group them in two ranges that have the least differences of width). This will avoid creating microscoping fragments that are hard or impossible to select.

But if it is only <=50% don't subdivide it at that level (you may still subdivide the other dimension to break two tiles by breaking on only one dimension instead of 4).

It should always be possible to subvidide in 2 or 4 for the next subquad size, even if the current tile is still not a square perfectly aligned on a "quad". Also creating tiny "islands" along border edges if the tile is not perfectly aligned to a quad: if the simple tiling would create too small subtiles (less than 1/4 of current quad size on one dimension, keep that small fragment with the tile on the other side.
This wil lstill allow creating a "grid-like" splitting that allows easy navigation and visualization, and easy selection.

**Comment by dakotabenjamin** [comment]
@verdy-p that has been solved as of version 3.1.0 (for projects created after the release)

But I can confirm the splitting bug in the OP is still present. (cc @russdeffner)

**Comment by xamanu** [comment]
This has been fixed in TM4.
