### ISSUE TITLE
TM3: Minimum page width (1033 pixels) is largely excessive and prevents too many users using TM

### ISSUE THREAD

**Issue by verdy-p** [hotosm/tasking-manager#820]
The minimum display width to use TM3 is excessive: 1033 pixels. At 1032 pixels we get an invitation to use Mapswipe instead.

Once again this is a issue of bad layout design. There's ample space to use TM3 on a desktop even when we want the browser only on half the width of the display, beside another window. It's even impossible to use it with some desktop if we have the developer console opened in the browser. The whole flowing of the layout is to rethink to be more versatile (think about flexible CSS and HTML layout designs).

I do not see really why TM3 should not work on a smartphone (with a flexible layout) even in portrait mode (about 640px wide should be enough: use tabs or similar to select what blocks to show seletively and be careful about encoding order of display blocks, use sliding menus if needed).

Even the tiles map should be renderable in that restricted width (provided you don't use the whole height and allow carefule sizing of titles, and don't waste excessive margins, and keep space at bottom for textual details, or a separate selectable tab (for the possibly long history and so on).

Avoid scrolling as much as possible, except for arbitrarily long lists such as the history or comments).

This was not so much a problem with TM2. So I see this as a regression bug.

**Comment by harry-wood** [comment]
The big red strip sending people to MapSwipe does feel like a web design cop out, but I can see why we've done it. Here it is at its widest:

![screen shot 2017-10-19 at 09 20 55](https://user-images.githubusercontent.com/227525/31761942-9b6639a2-b4b1-11e7-9cb6-55fdd6059333.png)

The website seems useable down to a bit narrower than that though. Maybe it should kick in at 750px, which I reckon is the point at which iD editor becomes not so useable anyway.

Worth thinking about iD editor use as a width constraint in the short term, since the key user flow we're catering for is launching of map editing sessions, however it's not the only user flow. In particular it's always desirable for a site visitor on mobile to have a reasonable viewing experience so that they're more likely to share a link to a TM project.

**Comment by pgiraud** [comment]
Possible solution: let the user dismiss the message (and ideally save the choice in LocalStorage).

**Comment by verdy-p** [comment]
I think it should not occur at 640px (half the screen of the 1280 wide desktop display)
at 640px, most modern smartphones should still be able to use TM.
But in order to detect small smarthpones, there's a better way to detect it. CSS offers `@media` filters for it or there are "user agent" detector libraries that can already instruct smartphones to also redirect to a dedicated app (loaded from Google Play or Apple AppStore or Windows Store) and associate the installed app with the domain (but I don't think there's an emergency to develop these mobile apps, and not even a Windows app for desktop Windows: we can stick on using only standard web site, which will still work on tablets that should all have a decent builtin web browser)
Don't think about restricting TM only to desktop PC users, there are many countries (and notably the poorest ones) where users only have smartphones or tablets
Even for deployed rescue teams on the field they'll want to have a view on ongoing projects directly on their smartphone even if they don't map directly in it. They should be able to give some details to projects or be able to add some "priority zone" drawn summarily.

**Comment by verdy-p** [comment]
Note that the initial minimum display width has even been increased now: when I created this bug it was 1033 pixels, now it's even larger (meaning that many more users see the red banner on their desktop browser asking them to go elsewhere)
