### ISSUE TITLE
Change link on front page disaster mapping?

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#838]
From https://github.com/hotosm/tasking-manager/pull/825#issuecomment-337855625 

For the home page:

`[...] I would link to http://tasks.hotosm.org/contribute?difficulty=ALL&campaign=Disaster%20Response instead of http://tasks.hotosm.org/contribute?difficulty=ALL&text=disaster`

**Comment by verdy-p** [comment]
we should be able to select more specific hashtags instead of random words taken in global descriptions. Frequently these descriptions are citing various partners or other related events (sometimes elsewhere) or past projects and it's difficult to filter them.
With a search by hashtag (those in default changeset comment) we would be more in focus as they are more unique.

However here the filter by campaign only may also be quite large (if we include difficulty=all) and when project admins and owners will also have in the list lot of archived tasks (we should be also able to add filter on status=published in the URL, to get results independantly of user's profile in TM)

And we need to fix the search by string in global contents to match exact text: for now only the single quote is used, but it is still a weak match, when traditional plain text searches use the double quote to match expressions (even if we ignore case differences and punctuation in plain text). So this requires improving the search engine for plain text searches (independantly of other possible filters: campaign, organization, difficulty, priority, geographic area/bbox, roads/buildings/etc. feature types, targetted mappers/validators roles)

**Comment by russdeffner** [comment]
@alekno - you probably want to let the project/tech managers do the assigning. Assigning this to me is about as good as assigning it to a tree.

@verdy-p - I think maybe you commented on the wrong issue? This issue is to simply change one link on the campaign descriptions.

**Comment by alekno** [comment]
@russdeffner the assigning has done its job to raise right peoples attention to this topic ;) This is no deep developing matter.

@verdy-p exactly.

**Comment by russdeffner** [comment]
@alekno - I don't think that's the point of assigning things in github and awareness does not equal results necessarily.

**Comment by verdy-p** [comment]
My comment was accurate by the fact you use an URL that specifies a plain text search, which is fuzzy and not finding all what is expected, and finding irrelevant results.
