### ISSUE TITLE
page title remains the same

### ISSUE THREAD

**Issue by pgiraud** [hotosm/tasking-manager#860]
Currently, the title of the page doesn't change during navigation from one step to another. It prevents users from going back to a specific step in the navigation history.
![screenshot from 2017-10-23 08-28-32](https://user-images.githubusercontent.com/319774/31875027-8c3e4f0a-b7cc-11e7-80bc-b106166caaa0.png)

**Comment by verdy-p** [comment]
This priority is raised because it evidently causes difficulty when navigating. It's not difficult to implement in code: each generated page should have an updated title containing the site name "HOT Tasking Manager" and the specific topic

Preferably in the order "(Topic) - HOT Tasking Manager" rather than the reverse, so tabs in browsers will still display a more specific part even if it is shown truncated ("HOT Tasking Manager" is not needed at begining, we already have a site icon at start, and browsers are already grouping pages for the same site when there are multiple sites in the user's history

**Comment by pgiraud** [comment]
> It's not difficult to implement in code

How do you know?

**Comment by verdy-p** [comment]
One line of code only to set a property...

Le 30 nov. 2017 12:46 PM, "Pierre GIRAUD" <notifications@github.com> a
écrit :

**Comment by pgiraud** [comment]
> One line of code only to set a property...

I'd be interested to see what change you would propose. Please provide a patch.

**Comment by ethan-nelson** [comment]
Sure @DorukUlucay , I will mark this as in progress!

**Comment by DorukUlucay** [comment]
I've sent a pr. Please do review.

**Comment by ethan-nelson** [comment]
This has been fixed in #1252
