### ISSUE TITLE
Allow PMs to map/validate/split tasks in "draft" or "archived" projects

### ISSUE THREAD

**Issue by verdy-p** [hotosm/tasking-manager#866]
When creating a project in TM3, the "draft" or "archived" state forbids any editing or splitting of unmapped tiles, or changing a mapped tile as "done" or invalidating it or marking it as "validated", EVEN for project admins or for the project creator, this is a regression compared to TM2.

**Comment by verdy-p** [comment]
adjusted to match the same tags as in #892 (an equivalent later report)

**Comment by bgirardot** [comment]
@verdy-p Please do not put "TM2 Regression" in the title of issues. There is a label for that now so it is redundant and makes the title of the issue hard to read.

**Comment by verdy-p** [comment]
it was there since the beginning, before you asked mer to add labels; at that time there was still no "regression" label that I created later.

**Comment by ethan-nelson** [comment]
For reference, this can be fixed with checking whether a user is a PM or admin near the beginning in https://github.com/hotosm/tasking-manager/blob/develop/server/services/project_service.py#L87-L116 and https://github.com/hotosm/tasking-manager/blob/develop/server/services/project_service.py#L132-L151

**Comment by bgirardot** [comment]
This should be all taken care of with the merges listed above
