### ISSUE TITLE
all feedback comments are very visible to all mappers

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#869]
When I validate I'll leave feedback saying tagged 23 untagged buildings.  Fine but the issue is negative feedback is OK to the mapper and anyone who looks at the tile but maybe off putting to a new mapper if their mistakes are so visible.

**Comment by alekno** [comment]
For really private feedback you can use the OSM message system. The TM messaging system is more about about an information protocol for following mappers on that specific task. TM is more about collaboration than ranting at someone.

**Comment by bgirardot** [comment]
Ya, leave messages that can be public and the @username thing.

That shows who the comment was directed to for new mappers reading past comments.

There is also the questions and answers tab you should be checking as a validator, kind of a side note though.

**Comment by bgirardot** [comment]
Hi @johnwhelan I am going to close this one for now.

The answer is to make sure your comments are friendly enough that a new mapper reading it would not be put off.

For example:

"I had to add the right tag to 23 buildings in your mapping. No problem at all, thank you for mapping. This happens because you did not click on the building 2 nd time to specify it was a building. Your outlines of the buildings were great, just need to add the building tag and they would be perfect! Nice work, thank you very much again!"

That should not scare off a newbie reading and it also would tell that newbie what to watch out for in their new mapping.

Much better than only the person who made the mistake getting the message.

Cheers, thanks for everything so far John, really appreciate your feedback and testing so far, here and on the HOT email list.

**Comment by bgirardot** [comment]
I do not see us adding in private messaging, as alekno said, if you need to send a private message the OSM system works for that and yes, you'd have to copy/paste the url of the task square.
