### ISSUE TITLE
Question and Comments - Notification

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#870]
Q/C section is great, but if you're like me and have hundreds of active projects; it's just not feasible to check them all regularly. Ideally it would be nice to have a 'separate' notification showing any 'unread' Q/C posts on projects or a simpler solution would be that the PM is just auto-included in any posts there vs. the mapper needing to hit the message PM link.

**Comment by bgirardot** [comment]
Hi Russ, I understand this issue.

Let us work with it as is for now, hopefully the "contact project manager" button will make sure the PMs are only getting things they need to.

I am afraid the Q/C from hundreds of projects might be overwhelming and lead to some being ignored.

But it would be easy enough to auto send them all to the PM if that is what turns out to be best.

**Comment by russdeffner** [comment]
An addition to this, it would be great if others could 'follow' a Q/C section.  I'm already seeing (including my own projects) that questions are going unanswered. I think this is even more important than quick validation; now that people are using the Q/C, if they don't get a response within a couple days, they are probably going to have a negative impression on the TM and HOT.  So, not only is it important that the project manager get a notification of new questions, others should be able to get that notification - i.e. validation team members during a response, etc.

**Comment by russdeffner** [comment]
Another related issue to this is maybe the project manager should always get notified and not rely on the mapper to hit the contact pm button.

**Comment by willemarcel** [comment]
I believe those notifications are enabled on TM4
