### ISSUE TITLE
Adding a comment to a task after validation

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#883]
How does one reply to a comment?

Ta John

**Comment by Boggedy** [comment]
I have taken validated tasks, sent an @johnwhelan type comment and it let me unlock at the very bottom (not revalidate) which triggered the sending of the comment. Even when a task was archived.

**Comment by bgirardot** [comment]
@johnwhelan ya, we really need to open up the comments on any task, checked out or not. That is the fix for this. In the mean time, generally what I do is reply via the questions and comments tab.

I am going to close this and label it 'work around exists' but I will make sure there is an issue to get the comment box back on the tasks regardless of if they are checked out or not.
