### ISSUE TITLE
Allow mapping and validating by project managers in draft and archived status

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#892]
Project managers (and probably validator role folks) need to be able to map and validate projects in draft and archived state. We do this very often as part of disaster response and typically missing maps project management.

![2017-10-28_16h32_25](https://user-images.githubusercontent.com/265831/32135343-da93b8ea-bbfd-11e7-977c-98ad0105435e.png)

**Comment by alekno** [comment]
Do we want validators doing archives/drafts?
I prefer a simple "mapping lock" in published projects but open for validators to validate and map. Can be done via metadata specification.

**Comment by verdy-p** [comment]
This is not a "refinement" but really a "regression bug" (compared to TM2) (regression of functionality). I have signaled it already several times since the TM3 launch.

Yes this is needed (even after going to "archived" state when project managers will want to perform some reviews and a few additional edits for local problems they may see once they have started using the exported data (this does not mean they'll be want to rever a tile from "validated" back to "invalidated" to have them done again, but I don't see why this could not happen.
The "published" state is only a tool for filtering by default what is visible by default and needs to be promoted. But maps in OSM are never definitely finished.

**Comment by verdy-p** [comment]
See the previously filed bug #866: this is the same

**Comment by alekno** [comment]
Maybe a new project state: Validation ( besides published, draft, archived). Validation projects only visible to validator role.

**Comment by verdy-p** [comment]
yes a "validating" state for the project as a whole (logically between "published" for mapping, and "archived") would be useful. But still this will be an unrelated "refinement" (not a regression as in this bug).

And we should not restrict editing tiles in a draft or archived project (including to "lock" a tile for mapping or validating, and in the locked state being able to "split" it or mark it as "done" or "validated" or "invalidated") independantly of the publication state of the project ("draft","mapping","validating","archived") - and especially (at least) not for project admins/creators!

**Comment by bgirardot** [comment]
@alekno @verdy-p The 'validating' status is an interesting idea we should revisit later.

For the moment, I would like to get things working at least as well as they worked in TM2 and focus on that.

I am going to close this one and go with verdy's issue #866
