### ISSUE TITLE
Add option to restrict editing programs allowed during validation

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#893]
and if you can't why is the option there?

**Comment by bgirardot** [comment]
I do not understand the question, could you expand more on it please?

Is it tasking manager related or iD related? There is an iD repository with issues as well if it might fit better there:

https://github.com/openstreetmap/iD

**Comment by johnwhelan** [comment]
By having iD as an option in on the validation page you are implying it is acceptable for validating.  So I would like confirmation that iD can detect crossing ways and untagged ways etc if it can't then please remove it from the list of acceptable editors for validation.

**Comment by Boggedy** [comment]
Good point. When one takes a task in HOT to validate it list of editors appears to the left of "Start Editing"

In many tasks iD is a crap choice and should not be offered for validating. It can be useful where the tiles are very small and the task is not a dense urban area. 

This can be dealt with when a task is created and an 'allow validation with iD option' is presented, default value unticked. If it is not ticked at task creation then iD should not appear on the list of editors available to the left of "start editor"

**Comment by tordans** [comment]
@bgirardot your last changes to the tags of this issue (mainly removing "question") suggest that you agree with this idea. I strongly disagree. I think it would be a big mistake to remove iD as a tool for validating.

If there is a real problem with the iD Editor, than please create an issue in the Repository at https://github.com/openstreetmap/iD/issues. 

At the very least, collect some data like usage stats from the app first, so you know how many validators would be affected. And maybe also on what kind of projects iD is used.

**Comment by johnwhelan** [comment]
The advantage of JOSM for validation is it has a number of built in checks
such as unclosed way.  It also has tools to detect duplicate buildings etc.
Knowing that JOSM has been used for validation gives an assurance that a
certain level of automated validation has been done.

There is more background in the wiki on the validation page.

Cheerio John

**Comment by Boggedy** [comment]
I am even more convinced that iD is a good beginners editor but that it is not suitable  for validation and is no better than Potlatch for error detection. 

If you add error detection to iD you scare off beginners who need to start somewhere before they eventually advance onto JOSM

I want iD removed from the list of editors that are valid for Validation tasks in HOTOSM, God only knows the amount of shite I cleaned up over the years to get a task over the line.

**Comment by bgirardot** [comment]
I hear this feedback and fully agree. 

How about an option on the project to no allow iD validation and we could default to that.

That does not fix your issue totally as there will still be mapping that is iD validated, but it should help a lot. You would also be able to choose to only work on projects that were JOSM validated since it would be a public flag on the project.

Yes, I think I just realized that iD has no way to check all the existing mapping for errors, only new mapping, that is a huge set back on validation. I do not really see how we can do the level of validation we want done without at least JOSM's validation.

**Comment by Boggedy** [comment]
iD checks for input errors but allows doozies like area=yes 

It does not check elements that already exist on the map. 

Josm validation is to say the least 'unfriendly' but most validators use JOSM and all the validators worth having do. I rarely find a perfect tasks when validating but my job is to ignore small errors and get it over the line by fixing them myself. 

Impossible to do in iD and it is also bloody slow ....and I have FTTH.

**Comment by Boggedy** [comment]
There is a related issue here,  validators should have a minimum 100 edits to their name. I think the solution for both is related to edit count and also to the software used to validate. 

https://github.com/hotosm/tasking-manager/issues/987

**Comment by johnwhelan** [comment]
> validators should have a minimum 100 edits to their name.

It's not a bad suggestion most of the time I'm not sure I agree all the
time.  I have used a team of validators before now.  Inexperienced but it
was a rush job and they were looking to check very specific things under my
direction.  I ran an eye over the tiles they were validating at the time
and handled any queries.  I couldn't have handled the amount of validation
required by myself in the time frame.

It was useful and the sheer number of problems they caught led to feedback
to the training working group about how things could be explained more
simply.

Cheerio John

**Comment by Boggedy** [comment]
I still think it should be 100 and thats for validators doing isolated buildings out the country or something. For urban tasks 100 edits is not enough.  

I'm just after validating a shanty town tile which took up a good 4-5 hours of experienced editor time. 
https://tasks.hotosm.org/project/4969?task=36#bottom

Letting a muppet with 5 edits to their name declaring it Valid would be an insult , frankly. :(

**Comment by Boggedy** [comment]
Thinking about Johns point some more I might have a suggested workaround.


1. no iD validators
2. 100 edit threshold for validators.
3.A  Global EXCEPTION to 1 and 2 above for 'invited validators' where a project creator can 'invite validators' whether they are over or under a threshold or use iD or JOSM.  

So an invitation screen in the project settings could be created where @ bgirardot  or @ Boggedy can be loaded and they are exempted from the global criteria 1 and 2 for that project.

Every experienced Project setter knows validators that they trust and this mechanism allows a personal message to be generated thru the HOTOSM message system asking them to help on whatever the project is and communicating things to watch for on that project etc.

**Comment by ethan-nelson** [comment]
Hi all, thank you for your feedback.

One of the important features identified in this discussion is adding the option to restrict validation based on the user level. I've changed #987 title a bit to reflect that intent. Furthermore, this issue is now tagged on there for folks to be able to see this discussion about that. Really, that option won't be too difficult to implement as much of the functionality with mapping restriction can be recycled.

The other feature is providing the _option_ for project managers to limit the editor used during validation, since some would still like the option for iD, and we can leave it up to the PM whether iD is included or not. So, I'm going to retitle this issue a bit to reflect that as the main goal of this issue.

Thanks again for all of your comments!

**Comment by Boggedy** [comment]
Nicely done Ethan.

**Comment by xamanu** [comment]
This has been resolved. Closing issue.
