### ISSUE TITLE
Completion Stats should not round up

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#909]
This is partially related to #829 

I almost archived a project because the stats showed 100% mapped and 100% validated; however, luckily I looked closer and saw there were several tasks still needing either mapping and/or validating. It appears the stats round up and that is causing the confusion.  It would be much better to truncate the stats percentage (i.e. show lower than actual completion) so mappers don't 'overlook'/look away from a project that is not complete because the stats are rounded up to 100%. It is already difficult to get mappers to take the last tasks without the tricky stats display.

**Comment by verdy-p** [comment]
It's true that since TM3, you can no longer do any mapping/validation work in a task which has a "draft" or "archived" status. There's already a bug for this: it should be allowed to do any editing/mapping/splitting/validation an any task independantly of the "published" status, if you are the project creator or a validator

Note that both creators and validators should see these projects, and that we still lack the filters that were in TM2 to selectively show them, and we also still lack the sort orders that were selectable in TM2, (here also there are bugs I submitted early just after the TM3 launch, which were then tagged as "regression", they are not really "UI improvements" but they had their use in TM2).

A summary view may still show "x%" (on the global or personal project lists), but on the detailed statistics for a specific project, we should see actual completions given as N/N tasks, not just the percentage computed on areas (with additional rounding errors if you cumulate rounded percentages, instead of cumulating actual areas...). This last bug also occured in TM2 and is not a regression since TM3.

**Comment by russdeffner** [comment]
@verdy-p that may all be true, but really the subject of my issue is literally one thing: "truncate instead of round the stats".

**Comment by Boggedy** [comment]
I would add an exception for 100% which is that 100% only means 100% and all % from 1 -99% are rounded. A fraction like 99.9% should show 99%

It helps maintain validation momentum I find.  Different code really, how to handle rounding above 99%.

**Comment by verdy-p** [comment]
I don't think it solves the case encountered were we actually found 101% [sic!], or also 99% (when ALL tiles have been completed and this should also be 100%) because we are still cumulating the rounded percentages instead of computing percentages by the ratio of two separately cumulated totals (now we'll cumulate the truncated percentages and chances are more likely to have a full completed project showing 99%, or even 98% or lower).
