### ISSUE TITLE
Changeset Comment Padding

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#914]
It appears the TM3 truncates the changeset comment.  I typically add one space after my default changeset comment, this makes it less likely the mapper will add their comment adjoined to a tracking hashtag. Example: want my cc to be "#PuertoRico " but ends up being "#PuertoRico"

**Comment by verdy-p** [comment]
I think only the trailing whitespace is trimmed. If you want to have others adjoining terms, you may want to use a punctuation after the last hashtag (I suggest the semicolon, or comma, rather than a full stop, colon or any dash that could be part of the same hashtag and even the same word).
But in fact, we don't need to do that and even store that whitespace: it can be added only on while creating and filling the HTML webform for input, so that any edit made by mappers will be to add new separate words, or replace the full comment (but the webform should have in memory the list of initial hashtags set from the project properties, and if any one of them is missing, they could be restored at start of the comment, if they were removed by editing: hashtags should be matched case-insensitively so that "#puertorico" or "#PuertoRico" would be equivalent and do not need to be duplicated).

Another solution: separate in the webform the list of hashtags from the rest of the comment, even if these will feed the same data field in the SQL database or the server API.

**Comment by ethan-nelson** [comment]
Hey Russ, do you recall this not happening in TM2? And is project 3665 an example of one you padded? I selected this project randomly as one you manage. Here is the path sent to iD:

`http://www.openstreetmap.org/edit?editor=id&#map=17/18.414472728477662/-66.20086668736046&comment=%23hotosm-project-3665%20%23HurricaneMaria%20%23PuertoRico%20&background=custom:https%3A%2F%2F%7Bswitch%3Aservices%2Cserver%7D.arcgisonline.com%2Farcgis%2Frest%2Fservices%2FWorld_Imagery%2FMapServer%2Ftile%2F%7Bz%7D%2F%7By%7D%2F%7Bx%7D&gpx=http%3A%2F%2Ftasks.hotosm.org%2Fapi%2Fv1%2Fproject%2F3665%2Ftasks_as_gpx%3Ftasks%3D965%26as_file%3Dfalse`

(which it looks like it does send an extra `%20`, or space, after `PuertoRico`.

And it looks like when I open it in JOSM, there is a space at the end of the changeset message. This makes me think it may be something with iD and not the TM3, but wanted to confirm.

**Comment by russdeffner** [comment]
@ethan-nelson Yes, this was never an issue with TM2; I do see the space is there in 3665, but that's an import from TM2 - 3782 is a new TM3 project and if you try to add a space, then save, it's gone again. So maybe there is an iD bug as well (don't use it often enough to remember it doing that before) but also seems new projects created in TM3 truncate space.

**Comment by russdeffner** [comment]
@ethan-nelson never mind my last comment, yes - this seems to be an iD thing; don't use it enough to remember if that happened with TM2 but I'll close this as it seems to work as expected at least on the TM3 side of things.

**Comment by ethan-nelson** [comment]
:+1: thanks for the follow-up Russ
