### ISSUE TITLE
checking a tile just validated

### ISSUE THREAD

**Issue by johnwhelan** [hotosm/tasking-manager#923]
With the new way of typing in the mapper's name I suspect I have misspelt one and sent the message to the wrong mapper.  I can't see a way to check this or get back to the tile I've just validated.

**Comment by bgirardot** [comment]
I think the issue here is that the task loses its selection after you mark it done/validated/invalidated or stop mapping. 

I think it should keep the focus, that would address this issue.

please see #924 I created as the replacement for this issue.

Also see #630 which would improve the activity and stats page to show everything that had happened to the project with more information and link to the task. Both of these would address this issue.

**Comment by belaeifert** [comment]
Hello! I would like to contribute with this issue. Which page can I see the bug?

**Comment by johnwhelan** [comment]
The issue was in the old version of the tasking manager it mas easier to
type the person's name.  You didn't need to type in every letter.

As Blake commented this is being addressed.

Cheerio John
