### ISSUE TITLE
Completion Stats - Validation should not be higher than Mapped

### ISSUE THREAD

**Issue by russdeffner** [hotosm/tasking-manager#945]
I noticed that project 3730 had a higher Validation percentage than Mapping percentage.  Looking at the project tasks, and later confirmed by @ethan-nelson that the tasks marked as "Bad Imagery" are taken into account in Validation percentage but not Mapping.

Here's what Ethan said on slack: 
it looks like mapped is fraction mapped over all tasks not including bad imagery, while validated is validated+bad imagery over all tasks (https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/project.py#L300-L301). that should perhaps be refined a bit

**Comment by johnwhelan** [comment]
The other comment is the only way to leave a comment at the moment is to open the tile for revalidation.  Does this get counted twice in the validation count?

John

**Comment by bgirardot** [comment]
Another example of a project where the percent mapped is lower than the percent validated. Further, the percent mapped shows as 98%, but when looking at the project, the whole thing is 100% validated.

https://tasks.hotosm.org/project/3815

**Comment by verdy-p** [comment]
I see 97% mapped 99% validated...

2017-12-06 18:29 GMT+01:00 Blake Girardot <notifications@github.com>:

**Comment by bgirardot** [comment]
@verdy-p Thank you very much verdy, i had not looked at the stats page, i was going by the card on the contribute list. This should help us figure out what is going on.

I know someone mentioned on another item that how it was calculated was different in the two places, but I can't locate that now.

But from the look of the graphic, it looks like it should be 100/100. Seems like it is probably related to the bad imagery option now available.

![2017-12-06_20h11_45](https://user-images.githubusercontent.com/265831/33680422-de7aae86-dac1-11e7-86d9-153b0018167b.png)
![2017-12-06_20h11_25](https://user-images.githubusercontent.com/265831/33680430-e28bbac4-dac1-11e7-93ed-45cc2ee532a8.png)
![2017-12-06_20h10_47](https://user-images.githubusercontent.com/265831/33680442-e9b9429e-dac1-11e7-8609-d7b5efb2ca5b.png)

**Comment by verdy-p** [comment]
Given the map is all green, there's no tile which is marked with "bad imagery" (it would be another color), but may be this occured in the past and a better imagery was used, the tile was invalidated and finally mapped and validated.
Is it possible that tiles that were present before a splitting are still counted and were not really marked as splitted and to ignore?

**Comment by pgiraud** [comment]
What do you think about this one?
<img width="456" alt="capture d ecran 2017-12-06 a 23 06 09" src="https://user-images.githubusercontent.com/319774/33688003-48d53e0a-dada-11e7-9562-1815061eb3ef.png">
https://tasks.hotosm.org/contribute?difficulty=ALL&text=3659

**Comment by verdy-p** [comment]
Most probably we are counting some initial tiles before their splitting that were left with an incoherent status.

Normally all tiles (tasks) that have been split should have in the database a reference to the original task number it comes from and which should be invisible (on the map, and in completion statistics) except for their attached history of comments (that we don't need to duplicate in every created subtask that replace the former task, but which should still be displayable by clicking a "more" link to exhibit the former task and its larger geometry on the rendered map after its first initial comment in the history of the subtask which indicates it was splitted from another task: we don't necessarily have to perform a recursive request, just following the link that will open the former task displayed at bottom of the history).

**Comment by eneedham** [comment]
I'm not sure if this should go here or be a separate issue, but % validated is over 100% and higher than % mapped. 

![image](https://user-images.githubusercontent.com/16779487/39473355-69cf5e74-4d1c-11e8-9ec0-b1f485eac569.png)

https://tasks.hotosm.org/project/4341

**Comment by bgirardot** [comment]
Some findings from testing:

Tasks marked "bad imagery" immediately count as "validated" task squares on the Activity and Stats page and the contribute list card for the project. They do not actually need to be validated, just marked bad imagery. They are not counted for mapping completion stats.

If they are then actually validated, they will count again for the validation stats on the activity and stats page and the contribute listing card leading to now double the actual validated task squres.  They are not counted for mapping completion stats.

If the bad imagery tasks that were validated, are then invalidated, one of their validation counts is removed, but the initial validation recorded for the bad imagery stats remains.

And, when invalidated, they are also deducted from the % mapped total, but they were never counted in the % mapped total in the first place so that % actually goes backward and negative if there is not enough actually mapped tasks to be covered.

If they are then actually mapped and marked "completely mapped" they will be recorded as mapped, but since invalidating them reduced the mapped % that had never been incremented when they were marked bad imagery in the first place, you will end up with mapped task squares that are not counted in the % mapped total.

I think the fix for these findings is to treat "bad imagery" tasks exactly like "completely mapped" tasks. that seems to work correctly.

Right now they are treated very differently and that is leading to issues.

We are finding more often than not, people are using the 'bad imagery' option incorrectly so those task squares end up being 'invalidated' to get them back into the mapping pool.

There is more testing to be done on this issue, but these initial findings would be a good start to fix this issue as I am sure this is a big part of the problem of bad numbers being displayed (< 100% mapped when it is 100% mapped and > 100% mapped or validated), regardless of them being different between activity and stats and the contribute listing.

**Comment by bgirardot** [comment]
Further testing:

Splitting those previous bad imagery, mapped, validate, invalidated tasks essentially wipes out any record of any activity on them or their impact on the project, with the exception of the mapped %.

That, in this case negative, percentage of mapped tasks was reduced because now there are more task squares so it went from -11% mapped to -7% (activity and stats) and -8% (contribution listing card).

**Comment by ethan-nelson** [comment]
I would say the majority of this behavior is corrected by the UI change suggested in #1123. However, there still seems to be a narrow case when the counters are not modified correctly just as you bring up:

In the event a validated task is later invalidated, [one is deducted not just from the validation counter but also the mapped counter](https://github.com/hotosm/tasking-manager/blob/032b02da8bee70f47a0638b1add6c01fec540b6a/server/services/stats_service.py#L104). I believe that means that, irrespective of a task being marked either mapped or bad imagery prior to the original validation, one is deducted from the mapped count. So [this line](https://github.com/hotosm/tasking-manager/blob/032b02da8bee70f47a0638b1add6c01fec540b6a/server/services/stats_service.py#L104) should check whether the most recent action other than validation/invalidation was set to mapped or bad imagery and then subtract one from the respective counter in addition to one from validation since [tasks marked as validated add to the validation count whether they are validation of a mapped or of a bad imagery](https://github.com/hotosm/tasking-manager/blob/032b02da8bee70f47a0638b1add6c01fec540b6a/server/services/stats_service.py#L49).

Another option would be to remove the bad imagery count altogether and lump it under the mapped count, but I think it is useful to know how many tiles are actually marked bad imagery. We just need to be certain that number remains consistent based on the actions that occur.

**Comment by xamanu** [comment]
Closed in favour of the follow up issue #1527
