### ISSUE TITLE
Improve tests and coverage

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#951]

**Comment by xamanu** [comment]
Hijacking this issue here. During the last week's tech team workshop we identified tests and test coverage to be one of our priorities to assure code and service quality around the Tasking Manager. With @ramyaragupathy I started a conversation about bringing up relevant test scenarios that urge most to us and get them implemented. Let's use this issue to progress on this side.

**Comment by xamanu** [comment]
First two cents from my side:

* Check whether a user who hasn't been logged in at all can do.
* Check whether the blocks of a blocked user are working (like selecting a task for mapping and validation or comment on any task or project).
* Test deployments before actual deployments

**Comment by JorgeMartinezG** [comment]
Code coverage was included in https://github.com/hotosm/tasking-manager/pull/799. Users can run tests and verify coverage in the `server` folder. However, during deployment and local tesing, there is no minimum coverage percentage value for Pull request to pass
