### ISSUE TITLE
Allow multiple project managers / organizations

### ISSUE THREAD

**Issue by mnoblecourt** [hotosm/tasking-manager#969]
For project managers working as a team, it would be useful that the original project manager (who created the project) can add additional PMs on a project, so that it also appears on their dashboard.
Same request for organizations although it might be more complex.

**Comment by verdy-p** [comment]
for organizations, they should also have their own profile, with one or a few  leaders (users) (allowed to managed this organization profile and the list of members), a list of additional coordinators, a list of sponsored projects (only leaders or coordinators should be allowed to add to/remove from this list), ans probably their own assesment of priorities (instead of the default global priority of projects) for sponsored projects shown on their profile.
Ideally, the TM projects themselves should also list the sponsoring organizations (for now there's a single one: the organization tag when editing projects: if the project manager adds an organization to his project, this should not be automatically added to the list of projects sponsored/followed by the selected organization, instead a notification will be visible in the organization's profile when editing it by the organization coordinators or leaders, saying that they are proposed to endorse it or not, and no one else than the organization's coordinators may remove a project from their list of sponsored/followed projects; and even if a project is "archived" or "drafted" in the global list of projects, it may be "published", and then editable by organization's coordinators/leaders, or workable for mapping/validating by contributors to the organization)
The organization profile would have properties similar to individual projects such as description (including contact means by mail, social networks, or websites), general instructions (including URL references to the OSM wiki), or reports of activities. And of course an organization would have an image (like normal users) generally used as an icon, plus possibly a large banner on at top of their profile.
An organization need be really registered as a legal organization, it may be any working group with some common interest (e.g. user groups of mappers in a region or cities organizing a single mapathon)

**Comment by mnoblecourt** [comment]
Following a discussion with Missing Maps partners: it would actually be interesting to have an organization dashboard showing all the projects for the organization but also overall stats for all projects (% mapped/validated, number of ongoing projects, etc.)
American Red Cross (@dalekunce) has started working on a similar tool and there is interest from Univ Heidelberg to help on that.
Also, possible to expand it to campaigns if the architecture allows? https://github.com/hotosm/tasking-manager/issues/583

**Comment by bgirardot** [comment]
Sure martin, pull requests are always welcome!

**Comment by xamanu** [comment]
There is some progress on several ends, that I think fit into this requirement here and I want to update and verify our thoughts here.

## Multiple organizations

We are currently redesigning the Tasking Manager and one very strong design assumption is to have exactly one organization per project:

![image](https://user-images.githubusercontent.com/97706/58174970-9fd13900-7c8e-11e9-9327-88c19629b8ff.png)

And we are improving a lot on how organizations #1531 & #1591 and #1590 can be improved from tags into teams and organizations with admins/managers. The campaigns are envisioned to group projects but can also belong to several organizations. This might be a good first step already into this direction and there is room for improvement.

But I think we should make this issue about one single feature -  to add multiple project managers to one project.

## Multiple project managers

The teams implementation is going to allow to assign groups of users (teams) to be assigned to one project for certain activities with the associated permissions: mapping, validation, project management. Administrators of the organization of the project will have project management permission, too.

In addition we may want to use this issue here to allow mappers, validators and project managers to be added, not only in teams, but also on a user basis. A simple autocomplete for each function/activity that allows project managers to select specific users.

**Comment by mnoblecourt** [comment]
Thanks for the update Felix - new interface looks great!
I think the combo organization=team you suggest would be great. I suggested the "several managers for a project" as a quick fix, but if all the managers within an organization can edit each other's project as you implied and have a common dashboard to visualize it, it's even better and we don't really need multiple project managers then (one could say there is one "main" manager but the responsibility ultimately on the organization/team).
One side question: I see a lot of Missing Maps-owned project on your screenshot, since one might be more tricky since MM is the "umbrella" under several team/orgs function. So to me MM would rather be a crosscutting campaign than a team.

**Comment by xamanu** [comment]
Yes, I agree MissingMaps is not a good "organization". The designs are mock-ups from the designers and the MM logos are better understood as placeholders. Confusing though, I agree :)

**Comment by xamanu** [comment]
Great. Then I suggest to close this issue in favor of the follow-ups #1531,  #1591 that will address the requested feature well. Thanks!

**Comment by russdeffner** [comment]
Just to toss a wrench - it may be true that MM is not an organization like the others; but take Cyclone Idai as example - the campaign was Cyclone Idai, operated by/as Missing Maps 'org'.
