### ISSUE TITLE
Add restriction option for validation level in project metadata

### ISSUE THREAD

**Issue by bgirardot** [hotosm/tasking-manager#987]
It would be nice if project managers could restrict validation to mappers who have intermediate and/or advanced level.

This would allow project managers to prevent very new mappers from validating, but not just restrict it to validators with the actual validation role.

I guess I would also include people with the actual validation role as well, even if they are not intermediate or advanced mappers.

(thank you for the suggestion @russdeffner )

**Comment by johnwhelan** [comment]
JOSM has a number of features and tools that help things that can detect duplicate buildings and the todo list.

Project Managers do not always know much about mapping, I've come across one who invalidated a tile because something had been mapped that wasn't on the project list.  Fine except it had been mapped a year before the project.

We don't have enough experienced validators so even an Id validation is better than nothing sometimes.  Having said that the PM's need a list of things that are not checked when validating with Id so they can get a better understanding of the issues before saying "Just do it" in Id.

**Comment by ramyaragupathy** [comment]
I'm going to give this a try 🔎

**Comment by russdeffner** [comment]
Thank you for working on this @ramyaragupathy, I was just coming to make this suggestion and happy to find that Blake did a while ago and you're working on it!

**Comment by xamanu** [comment]
This has been addressed by @ramyaragupathy in #1313
